//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.02 at 06:39:37 PM CEST 
//


package es.ehubio.proteomics.psi.mzid11;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Data sets generated by the analyses, including peptide and protein lists. 
 * 
 * <p>Java class for AnalysisDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnalysisDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SpectrumIdentificationList" type="{http://psidev.info/psi/pi/mzIdentML/1.1}SpectrumIdentificationListType" maxOccurs="unbounded"/>
 *         &lt;element name="ProteinDetectionList" type="{http://psidev.info/psi/pi/mzIdentML/1.1}ProteinDetectionListType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnalysisDataType", propOrder = {
    "spectrumIdentificationLists",
    "proteinDetectionList"
})
public class AnalysisDataType {

    @XmlElement(name = "SpectrumIdentificationList", required = true)
    protected List<SpectrumIdentificationListType> spectrumIdentificationLists;
    @XmlElement(name = "ProteinDetectionList")
    protected ProteinDetectionListType proteinDetectionList;

    /**
     * Gets the value of the spectrumIdentificationLists property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the spectrumIdentificationLists property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpectrumIdentificationLists().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SpectrumIdentificationListType }
     * 
     * 
     */
    public List<SpectrumIdentificationListType> getSpectrumIdentificationLists() {
        if (spectrumIdentificationLists == null) {
            spectrumIdentificationLists = new ArrayList<SpectrumIdentificationListType>();
        }
        return this.spectrumIdentificationLists;
    }

    /**
     * Gets the value of the proteinDetectionList property.
     * 
     * @return
     *     possible object is
     *     {@link ProteinDetectionListType }
     *     
     */
    public ProteinDetectionListType getProteinDetectionList() {
        return proteinDetectionList;
    }

    /**
     * Sets the value of the proteinDetectionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProteinDetectionListType }
     *     
     */
    public void setProteinDetectionList(ProteinDetectionListType value) {
        this.proteinDetectionList = value;
    }

}
