//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.02 at 06:39:37 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://psidev.info/psi/pi/mzIdentML/1.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package es.ehubio.proteomics.psi.mzid11;
