// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
// This source code was auto-generated by Web Services Description Language Utility
//Mono Framework v4.0.30319.1
//

namespace EhuBio.Database.Ncbi.eUtils {

/// <remarks/>
[System.Web.Services.WebServiceBinding(Name="eUtilsServiceSoap", Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class eUtilsService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback run_eGqueryOperationCompleted;
    
    private System.Threading.SendOrPostCallback run_eInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback run_eSearchOperationCompleted;
    
    private System.Threading.SendOrPostCallback run_eSummaryOperationCompleted;
    
    private System.Threading.SendOrPostCallback run_eLinkOperationCompleted;
    
    private System.Threading.SendOrPostCallback run_eSpellOperationCompleted;
    
    private System.Threading.SendOrPostCallback run_ePostOperationCompleted;
    
    public eUtilsService() {
        this.Url = "http://eutils.ncbi.nlm.nih.gov/soap/v2.0/soap_adapter_2_0.cgi";
    }
    
    public event run_eGqueryCompletedEventHandler run_eGqueryCompleted;
    
    public event run_eInfoCompletedEventHandler run_eInfoCompleted;
    
    public event run_eSearchCompletedEventHandler run_eSearchCompleted;
    
    public event run_eSummaryCompletedEventHandler run_eSummaryCompleted;
    
    public event run_eLinkCompletedEventHandler run_eLinkCompleted;
    
    public event run_eSpellCompletedEventHandler run_eSpellCompleted;
    
    public event run_ePostCompletedEventHandler run_ePostCompleted;
    
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("egquery", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("Result", Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/egquery")]
    public MessageResult run_eGquery([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/egquery")] MessageEGqueryRequest eGqueryRequest) {
        object[] results = this.Invoke("run_eGquery", new object[] {
                    eGqueryRequest});
        return ((MessageResult)(results[0]));
    }
    
    public System.IAsyncResult Beginrun_eGquery(MessageEGqueryRequest eGqueryRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("run_eGquery", new object[] {
                    eGqueryRequest}, callback, asyncState);
    }
    
    public MessageResult Endrun_eGquery(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((MessageResult)(results[0]));
    }
    
    public void run_eGqueryAsync(MessageEGqueryRequest eGqueryRequest) {
        this.run_eGqueryAsync(eGqueryRequest, null);
    }
    
    public void run_eGqueryAsync(MessageEGqueryRequest eGqueryRequest, object userState) {
        if ((this.run_eGqueryOperationCompleted == null)) {
            this.run_eGqueryOperationCompleted = new System.Threading.SendOrPostCallback(this.Onrun_eGqueryCompleted);
        }
        this.InvokeAsync("run_eGquery", new object[] {
                    eGqueryRequest}, this.run_eGqueryOperationCompleted, userState);
    }
    
    private void Onrun_eGqueryCompleted(object arg) {
        if ((this.run_eGqueryCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.run_eGqueryCompleted(this, new run_eGqueryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("einfo", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("eInfoResult", Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/einfo")]
    public MessageEInfoResult run_eInfo([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/einfo")] MessageEInfoRequest eInfoRequest) {
        object[] results = this.Invoke("run_eInfo", new object[] {
                    eInfoRequest});
        return ((MessageEInfoResult)(results[0]));
    }
    
    public System.IAsyncResult Beginrun_eInfo(MessageEInfoRequest eInfoRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("run_eInfo", new object[] {
                    eInfoRequest}, callback, asyncState);
    }
    
    public MessageEInfoResult Endrun_eInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((MessageEInfoResult)(results[0]));
    }
    
    public void run_eInfoAsync(MessageEInfoRequest eInfoRequest) {
        this.run_eInfoAsync(eInfoRequest, null);
    }
    
    public void run_eInfoAsync(MessageEInfoRequest eInfoRequest, object userState) {
        if ((this.run_eInfoOperationCompleted == null)) {
            this.run_eInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.Onrun_eInfoCompleted);
        }
        this.InvokeAsync("run_eInfo", new object[] {
                    eInfoRequest}, this.run_eInfoOperationCompleted, userState);
    }
    
    private void Onrun_eInfoCompleted(object arg) {
        if ((this.run_eInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.run_eInfoCompleted(this, new run_eInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("esearch", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("eSearchResult", Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/esearch")]
    public MessageESearchResult run_eSearch([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/esearch")] MessageESearchRequest eSearchRequest) {
        object[] results = this.Invoke("run_eSearch", new object[] {
                    eSearchRequest});
        return ((MessageESearchResult)(results[0]));
    }
    
    public System.IAsyncResult Beginrun_eSearch(MessageESearchRequest eSearchRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("run_eSearch", new object[] {
                    eSearchRequest}, callback, asyncState);
    }
    
    public MessageESearchResult Endrun_eSearch(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((MessageESearchResult)(results[0]));
    }
    
    public void run_eSearchAsync(MessageESearchRequest eSearchRequest) {
        this.run_eSearchAsync(eSearchRequest, null);
    }
    
    public void run_eSearchAsync(MessageESearchRequest eSearchRequest, object userState) {
        if ((this.run_eSearchOperationCompleted == null)) {
            this.run_eSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.Onrun_eSearchCompleted);
        }
        this.InvokeAsync("run_eSearch", new object[] {
                    eSearchRequest}, this.run_eSearchOperationCompleted, userState);
    }
    
    private void Onrun_eSearchCompleted(object arg) {
        if ((this.run_eSearchCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.run_eSearchCompleted(this, new run_eSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("esummary", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("eSummaryResult", Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/esummary")]
    public MessageESummaryResult run_eSummary([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/esummary")] MessageESummaryRequest eSummaryRequest) {
        object[] results = this.Invoke("run_eSummary", new object[] {
                    eSummaryRequest});
        return ((MessageESummaryResult)(results[0]));
    }
    
    public System.IAsyncResult Beginrun_eSummary(MessageESummaryRequest eSummaryRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("run_eSummary", new object[] {
                    eSummaryRequest}, callback, asyncState);
    }
    
    public MessageESummaryResult Endrun_eSummary(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((MessageESummaryResult)(results[0]));
    }
    
    public void run_eSummaryAsync(MessageESummaryRequest eSummaryRequest) {
        this.run_eSummaryAsync(eSummaryRequest, null);
    }
    
    public void run_eSummaryAsync(MessageESummaryRequest eSummaryRequest, object userState) {
        if ((this.run_eSummaryOperationCompleted == null)) {
            this.run_eSummaryOperationCompleted = new System.Threading.SendOrPostCallback(this.Onrun_eSummaryCompleted);
        }
        this.InvokeAsync("run_eSummary", new object[] {
                    eSummaryRequest}, this.run_eSummaryOperationCompleted, userState);
    }
    
    private void Onrun_eSummaryCompleted(object arg) {
        if ((this.run_eSummaryCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.run_eSummaryCompleted(this, new run_eSummaryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("elink", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("eLinkResult", Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/elink")]
    public MessageELinkResult run_eLink([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/elink")] MessageELinkRequest eLinkRequest) {
        object[] results = this.Invoke("run_eLink", new object[] {
                    eLinkRequest});
        return ((MessageELinkResult)(results[0]));
    }
    
    public System.IAsyncResult Beginrun_eLink(MessageELinkRequest eLinkRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("run_eLink", new object[] {
                    eLinkRequest}, callback, asyncState);
    }
    
    public MessageELinkResult Endrun_eLink(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((MessageELinkResult)(results[0]));
    }
    
    public void run_eLinkAsync(MessageELinkRequest eLinkRequest) {
        this.run_eLinkAsync(eLinkRequest, null);
    }
    
    public void run_eLinkAsync(MessageELinkRequest eLinkRequest, object userState) {
        if ((this.run_eLinkOperationCompleted == null)) {
            this.run_eLinkOperationCompleted = new System.Threading.SendOrPostCallback(this.Onrun_eLinkCompleted);
        }
        this.InvokeAsync("run_eLink", new object[] {
                    eLinkRequest}, this.run_eLinkOperationCompleted, userState);
    }
    
    private void Onrun_eLinkCompleted(object arg) {
        if ((this.run_eLinkCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.run_eLinkCompleted(this, new run_eLinkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("espell", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("eSpellResult", Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/espell")]
    public MessageESpellResult run_eSpell([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/espell")] MessageESpellRequest eSpellRequest) {
        object[] results = this.Invoke("run_eSpell", new object[] {
                    eSpellRequest});
        return ((MessageESpellResult)(results[0]));
    }
    
    public System.IAsyncResult Beginrun_eSpell(MessageESpellRequest eSpellRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("run_eSpell", new object[] {
                    eSpellRequest}, callback, asyncState);
    }
    
    public MessageESpellResult Endrun_eSpell(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((MessageESpellResult)(results[0]));
    }
    
    public void run_eSpellAsync(MessageESpellRequest eSpellRequest) {
        this.run_eSpellAsync(eSpellRequest, null);
    }
    
    public void run_eSpellAsync(MessageESpellRequest eSpellRequest, object userState) {
        if ((this.run_eSpellOperationCompleted == null)) {
            this.run_eSpellOperationCompleted = new System.Threading.SendOrPostCallback(this.Onrun_eSpellCompleted);
        }
        this.InvokeAsync("run_eSpell", new object[] {
                    eSpellRequest}, this.run_eSpellOperationCompleted, userState);
    }
    
    private void Onrun_eSpellCompleted(object arg) {
        if ((this.run_eSpellCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.run_eSpellCompleted(this, new run_eSpellCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("epost", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("ePostResult", Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/epost")]
    public MessageEPostResult run_ePost([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/epost")] MessageEPostRequest ePostRequest) {
        object[] results = this.Invoke("run_ePost", new object[] {
                    ePostRequest});
        return ((MessageEPostResult)(results[0]));
    }
    
    public System.IAsyncResult Beginrun_ePost(MessageEPostRequest ePostRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("run_ePost", new object[] {
                    ePostRequest}, callback, asyncState);
    }
    
    public MessageEPostResult Endrun_ePost(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((MessageEPostResult)(results[0]));
    }
    
    public void run_ePostAsync(MessageEPostRequest ePostRequest) {
        this.run_ePostAsync(ePostRequest, null);
    }
    
    public void run_ePostAsync(MessageEPostRequest ePostRequest, object userState) {
        if ((this.run_ePostOperationCompleted == null)) {
            this.run_ePostOperationCompleted = new System.Threading.SendOrPostCallback(this.Onrun_ePostCompleted);
        }
        this.InvokeAsync("run_ePost", new object[] {
                    ePostRequest}, this.run_ePostOperationCompleted, userState);
    }
    
    private void Onrun_ePostCompleted(object arg) {
        if ((this.run_ePostCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.run_ePostCompleted(this, new run_ePostCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/egquery")]
[System.Xml.Serialization.XmlRootAttribute("eGqueryRequest", Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/egquery")]
public partial class MessageEGqueryRequest {
    
    private string termField;
    
    private string toolField;
    
    private string emailField;
    
    /// <remarks/>
    public string term {
        get {
            return this.termField;
        }
        set {
            this.termField = value;
        }
    }
    
    /// <remarks/>
    public string tool {
        get {
            return this.toolField;
        }
        set {
            this.toolField = value;
        }
    }
    
    /// <remarks/>
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/egquery")]
[System.Xml.Serialization.XmlRootAttribute("Result", Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/egquery")]
public partial class MessageResult {
    
    private string termField1;
    
    private eGQueryResultType eGQueryResultField;
    
    /// <remarks/>
    public string Term {
        get {
            return this.termField1;
        }
        set {
            this.termField1 = value;
        }
    }
    
    /// <remarks/>
    public eGQueryResultType eGQueryResult {
        get {
            return this.eGQueryResultField;
        }
        set {
            this.eGQueryResultField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/egquery")]
public partial class eGQueryResultType {
    
    private string eRRORField;
    
    private ResultItemType[] resultItemField;
    
    /// <remarks/>
    public string ERROR {
        get {
            return this.eRRORField;
        }
        set {
            this.eRRORField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ResultItem")]
    public ResultItemType[] ResultItem {
        get {
            return this.resultItemField;
        }
        set {
            this.resultItemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/egquery")]
public partial class ResultItemType {
    
    private string dbNameField;
    
    private string menuNameField;
    
    private string countField;
    
    private string statusField;
    
    /// <remarks/>
    public string DbName {
        get {
            return this.dbNameField;
        }
        set {
            this.dbNameField = value;
        }
    }
    
    /// <remarks/>
    public string MenuName {
        get {
            return this.menuNameField;
        }
        set {
            this.menuNameField = value;
        }
    }
    
    /// <remarks/>
    public string Count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
    
    /// <remarks/>
    public string Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/einfo")]
[System.Xml.Serialization.XmlRootAttribute("eInfoRequest", Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/einfo")]
public partial class MessageEInfoRequest {
    
    private string dbField;
    
    private string toolField1;
    
    private string emailField1;
    
    /// <remarks/>
    public string db {
        get {
            return this.dbField;
        }
        set {
            this.dbField = value;
        }
    }
    
    /// <remarks/>
    public string tool {
        get {
            return this.toolField1;
        }
        set {
            this.toolField1 = value;
        }
    }
    
    /// <remarks/>
    public string email {
        get {
            return this.emailField1;
        }
        set {
            this.emailField1 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/einfo")]
[System.Xml.Serialization.XmlRootAttribute("eInfoResult", Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/einfo")]
public partial class MessageEInfoResult {
    
    private string eRRORField1;
    
    private string[] dbListField;
    
    private DbInfoType dbInfoField;
    
    /// <remarks/>
    public string ERROR {
        get {
            return this.eRRORField1;
        }
        set {
            this.eRRORField1 = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(ElementName="DbName", IsNullable=false)]
    public string[] DbList {
        get {
            return this.dbListField;
        }
        set {
            this.dbListField = value;
        }
    }
    
    /// <remarks/>
    public DbInfoType DbInfo {
        get {
            return this.dbInfoField;
        }
        set {
            this.dbInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/einfo")]
public partial class DbInfoType {
    
    private string dbNameField1;
    
    private string menuNameField1;
    
    private string descriptionField;
    
    private string countField1;
    
    private string lastUpdateField;
    
    private FieldType[] fieldListField;
    
    private LinkType[] linkListField;
    
    /// <remarks/>
    public string DbName {
        get {
            return this.dbNameField1;
        }
        set {
            this.dbNameField1 = value;
        }
    }
    
    /// <remarks/>
    public string MenuName {
        get {
            return this.menuNameField1;
        }
        set {
            this.menuNameField1 = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string Count {
        get {
            return this.countField1;
        }
        set {
            this.countField1 = value;
        }
    }
    
    /// <remarks/>
    public string LastUpdate {
        get {
            return this.lastUpdateField;
        }
        set {
            this.lastUpdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(ElementName="Field", IsNullable=false)]
    public FieldType[] FieldList {
        get {
            return this.fieldListField;
        }
        set {
            this.fieldListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(ElementName="Link", IsNullable=false)]
    public LinkType[] LinkList {
        get {
            return this.linkListField;
        }
        set {
            this.linkListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/einfo")]
public partial class FieldType {
    
    private string nameField;
    
    private string fullNameField;
    
    private string descriptionField1;
    
    private string termCountField;
    
    private string isDateField;
    
    private string isNumericalField;
    
    private string singleTokenField;
    
    private string hierarchyField;
    
    private string isHiddenField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string FullName {
        get {
            return this.fullNameField;
        }
        set {
            this.fullNameField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField1;
        }
        set {
            this.descriptionField1 = value;
        }
    }
    
    /// <remarks/>
    public string TermCount {
        get {
            return this.termCountField;
        }
        set {
            this.termCountField = value;
        }
    }
    
    /// <remarks/>
    public string IsDate {
        get {
            return this.isDateField;
        }
        set {
            this.isDateField = value;
        }
    }
    
    /// <remarks/>
    public string IsNumerical {
        get {
            return this.isNumericalField;
        }
        set {
            this.isNumericalField = value;
        }
    }
    
    /// <remarks/>
    public string SingleToken {
        get {
            return this.singleTokenField;
        }
        set {
            this.singleTokenField = value;
        }
    }
    
    /// <remarks/>
    public string Hierarchy {
        get {
            return this.hierarchyField;
        }
        set {
            this.hierarchyField = value;
        }
    }
    
    /// <remarks/>
    public string IsHidden {
        get {
            return this.isHiddenField;
        }
        set {
            this.isHiddenField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/einfo")]
public partial class LinkType {
    
    private string nameField1;
    
    private string menuField;
    
    private string descriptionField2;
    
    private string dbToField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField1;
        }
        set {
            this.nameField1 = value;
        }
    }
    
    /// <remarks/>
    public string Menu {
        get {
            return this.menuField;
        }
        set {
            this.menuField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField2;
        }
        set {
            this.descriptionField2 = value;
        }
    }
    
    /// <remarks/>
    public string DbTo {
        get {
            return this.dbToField;
        }
        set {
            this.dbToField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/esearch")]
[System.Xml.Serialization.XmlRootAttribute("eSearchRequest", Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/esearch")]
public partial class MessageESearchRequest {
    
    private string dbField1;
    
    private string termField2;
    
    private string webEnvField;
    
    private string queryKeyField;
    
    private string usehistoryField;
    
    private string toolField2;
    
    private string emailField2;
    
    private string fieldField;
    
    private string reldateField;
    
    private string mindateField;
    
    private string maxdateField;
    
    private string datetypeField;
    
    private string retStartField;
    
    private string retMaxField;
    
    private string rettypeField;
    
    private string sortField;
    
    /// <remarks/>
    public string db {
        get {
            return this.dbField1;
        }
        set {
            this.dbField1 = value;
        }
    }
    
    /// <remarks/>
    public string term {
        get {
            return this.termField2;
        }
        set {
            this.termField2 = value;
        }
    }
    
    /// <remarks/>
    public string WebEnv {
        get {
            return this.webEnvField;
        }
        set {
            this.webEnvField = value;
        }
    }
    
    /// <remarks/>
    public string QueryKey {
        get {
            return this.queryKeyField;
        }
        set {
            this.queryKeyField = value;
        }
    }
    
    /// <remarks/>
    public string usehistory {
        get {
            return this.usehistoryField;
        }
        set {
            this.usehistoryField = value;
        }
    }
    
    /// <remarks/>
    public string tool {
        get {
            return this.toolField2;
        }
        set {
            this.toolField2 = value;
        }
    }
    
    /// <remarks/>
    public string email {
        get {
            return this.emailField2;
        }
        set {
            this.emailField2 = value;
        }
    }
    
    /// <remarks/>
    public string field {
        get {
            return this.fieldField;
        }
        set {
            this.fieldField = value;
        }
    }
    
    /// <remarks/>
    public string reldate {
        get {
            return this.reldateField;
        }
        set {
            this.reldateField = value;
        }
    }
    
    /// <remarks/>
    public string mindate {
        get {
            return this.mindateField;
        }
        set {
            this.mindateField = value;
        }
    }
    
    /// <remarks/>
    public string maxdate {
        get {
            return this.maxdateField;
        }
        set {
            this.maxdateField = value;
        }
    }
    
    /// <remarks/>
    public string datetype {
        get {
            return this.datetypeField;
        }
        set {
            this.datetypeField = value;
        }
    }
    
    /// <remarks/>
    public string RetStart {
        get {
            return this.retStartField;
        }
        set {
            this.retStartField = value;
        }
    }
    
    /// <remarks/>
    public string RetMax {
        get {
            return this.retMaxField;
        }
        set {
            this.retMaxField = value;
        }
    }
    
    /// <remarks/>
    public string rettype {
        get {
            return this.rettypeField;
        }
        set {
            this.rettypeField = value;
        }
    }
    
    /// <remarks/>
    public string sort {
        get {
            return this.sortField;
        }
        set {
            this.sortField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/esearch")]
[System.Xml.Serialization.XmlRootAttribute("eSearchResult", Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/esearch")]
public partial class MessageESearchResult {
    
    private string eRRORField2;
    
    private string countField2;
    
    private string retMaxField1;
    
    private string retStartField1;
    
    private string queryKeyField1;
    
    private string webEnvField1;
    
    private string[] idListField;
    
    private TranslationType[] translationSetField;
    
    private object[] translationStackField;
    
    private string queryTranslationField;
    
    private ErrorListType errorListField;
    
    private WarningListType warningListField;
    
    /// <remarks/>
    public string ERROR {
        get {
            return this.eRRORField2;
        }
        set {
            this.eRRORField2 = value;
        }
    }
    
    /// <remarks/>
    public string Count {
        get {
            return this.countField2;
        }
        set {
            this.countField2 = value;
        }
    }
    
    /// <remarks/>
    public string RetMax {
        get {
            return this.retMaxField1;
        }
        set {
            this.retMaxField1 = value;
        }
    }
    
    /// <remarks/>
    public string RetStart {
        get {
            return this.retStartField1;
        }
        set {
            this.retStartField1 = value;
        }
    }
    
    /// <remarks/>
    public string QueryKey {
        get {
            return this.queryKeyField1;
        }
        set {
            this.queryKeyField1 = value;
        }
    }
    
    /// <remarks/>
    public string WebEnv {
        get {
            return this.webEnvField1;
        }
        set {
            this.webEnvField1 = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(ElementName="Id", IsNullable=false)]
    public string[] IdList {
        get {
            return this.idListField;
        }
        set {
            this.idListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(ElementName="Translation", IsNullable=false)]
    public TranslationType[] TranslationSet {
        get {
            return this.translationSetField;
        }
        set {
            this.translationSetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(ElementName="TermSet", Type=typeof(TermSetType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItem(ElementName="OP", Type=typeof(string), IsNullable=false)]
    public object[] TranslationStack {
        get {
            return this.translationStackField;
        }
        set {
            this.translationStackField = value;
        }
    }
    
    /// <remarks/>
    public string QueryTranslation {
        get {
            return this.queryTranslationField;
        }
        set {
            this.queryTranslationField = value;
        }
    }
    
    /// <remarks/>
    public ErrorListType ErrorList {
        get {
            return this.errorListField;
        }
        set {
            this.errorListField = value;
        }
    }
    
    /// <remarks/>
    public WarningListType WarningList {
        get {
            return this.warningListField;
        }
        set {
            this.warningListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/esearch")]
public partial class TranslationType {
    
    private string fromField;
    
    private string toField;
    
    /// <remarks/>
    public string From {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <remarks/>
    public string To {
        get {
            return this.toField;
        }
        set {
            this.toField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/esearch")]
public partial class TermSetType {
    
    private string termField3;
    
    private string fieldField1;
    
    private string countField3;
    
    private string explodeField;
    
    /// <remarks/>
    public string Term {
        get {
            return this.termField3;
        }
        set {
            this.termField3 = value;
        }
    }
    
    /// <remarks/>
    public string Field {
        get {
            return this.fieldField1;
        }
        set {
            this.fieldField1 = value;
        }
    }
    
    /// <remarks/>
    public string Count {
        get {
            return this.countField3;
        }
        set {
            this.countField3 = value;
        }
    }
    
    /// <remarks/>
    public string Explode {
        get {
            return this.explodeField;
        }
        set {
            this.explodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/esearch")]
public partial class ErrorListType {
    
    private string[] phraseNotFoundField;
    
    private string[] fieldNotFoundField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PhraseNotFound")]
    public string[] PhraseNotFound {
        get {
            return this.phraseNotFoundField;
        }
        set {
            this.phraseNotFoundField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FieldNotFound")]
    public string[] FieldNotFound {
        get {
            return this.fieldNotFoundField;
        }
        set {
            this.fieldNotFoundField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/esearch")]
public partial class WarningListType {
    
    private string[] phraseIgnoredField;
    
    private string[] quotedPhraseNotFoundField;
    
    private string[] outputMessageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PhraseIgnored")]
    public string[] PhraseIgnored {
        get {
            return this.phraseIgnoredField;
        }
        set {
            this.phraseIgnoredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("QuotedPhraseNotFound")]
    public string[] QuotedPhraseNotFound {
        get {
            return this.quotedPhraseNotFoundField;
        }
        set {
            this.quotedPhraseNotFoundField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OutputMessage")]
    public string[] OutputMessage {
        get {
            return this.outputMessageField;
        }
        set {
            this.outputMessageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/esummary")]
[System.Xml.Serialization.XmlRootAttribute("eSummaryRequest", Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/esummary")]
public partial class MessageESummaryRequest {
    
    private string dbField2;
    
    private string idField;
    
    private string webEnvField2;
    
    private string query_keyField;
    
    private string retstartField;
    
    private string retmaxField;
    
    private string toolField3;
    
    private string emailField3;
    
    /// <remarks/>
    public string db {
        get {
            return this.dbField2;
        }
        set {
            this.dbField2 = value;
        }
    }
    
    /// <remarks/>
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string WebEnv {
        get {
            return this.webEnvField2;
        }
        set {
            this.webEnvField2 = value;
        }
    }
    
    /// <remarks/>
    public string query_key {
        get {
            return this.query_keyField;
        }
        set {
            this.query_keyField = value;
        }
    }
    
    /// <remarks/>
    public string retstart {
        get {
            return this.retstartField;
        }
        set {
            this.retstartField = value;
        }
    }
    
    /// <remarks/>
    public string retmax {
        get {
            return this.retmaxField;
        }
        set {
            this.retmaxField = value;
        }
    }
    
    /// <remarks/>
    public string tool {
        get {
            return this.toolField3;
        }
        set {
            this.toolField3 = value;
        }
    }
    
    /// <remarks/>
    public string email {
        get {
            return this.emailField3;
        }
        set {
            this.emailField3 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/esummary")]
[System.Xml.Serialization.XmlRootAttribute("eSummaryResult", Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/esummary")]
public partial class MessageESummaryResult {
    
    private string eRRORField3;
    
    private DocSumType[] docSumField;
    
    /// <remarks/>
    public string ERROR {
        get {
            return this.eRRORField3;
        }
        set {
            this.eRRORField3 = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DocSum")]
    public DocSumType[] DocSum {
        get {
            return this.docSumField;
        }
        set {
            this.docSumField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/esummary")]
public partial class DocSumType {
    
    private string idField1;
    
    private ItemType[] itemField;
    
    /// <remarks/>
    public string Id {
        get {
            return this.idField1;
        }
        set {
            this.idField1 = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Item")]
    public ItemType[] Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/esummary")]
public partial class ItemType {
    
    private string nameField2;
    
    private ItemTypeType typeField;
    
    private ItemType[] itemField1;
    
    private string itemContentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
    public string Name {
        get {
            return this.nameField2;
        }
        set {
            this.nameField2 = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
    public ItemTypeType Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Item")]
    public ItemType[] Item {
        get {
            return this.itemField1;
        }
        set {
            this.itemField1 = value;
        }
    }
    
    /// <remarks/>
    public string ItemContent {
        get {
            return this.itemContentField;
        }
        set {
            this.itemContentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/esummary")]
public enum ItemTypeType {
    
    /// <remarks/>
    Integer,
    
    /// <remarks/>
    Date,
    
    /// <remarks/>
    String,
    
    /// <remarks/>
    Structure,
    
    /// <remarks/>
    List,
    
    /// <remarks/>
    Flags,
    
    /// <remarks/>
    Qualifier,
    
    /// <remarks/>
    Enumerator,
    
    /// <remarks/>
    Unknown,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/elink")]
[System.Xml.Serialization.XmlRootAttribute("eLinkRequest", Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/elink")]
public partial class MessageELinkRequest {
    
    private string dbField3;
    
    private string[] idField2;
    
    private string reldateField1;
    
    private string mindateField1;
    
    private string maxdateField1;
    
    private string datetypeField1;
    
    private string termField4;
    
    private string dbfromField;
    
    private string linknameField;
    
    private string webEnvField3;
    
    private string query_keyField1;
    
    private string cmdField;
    
    private string toolField4;
    
    private string emailField4;
    
    /// <remarks/>
    public string db {
        get {
            return this.dbField3;
        }
        set {
            this.dbField3 = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("id")]
    public string[] id {
        get {
            return this.idField2;
        }
        set {
            this.idField2 = value;
        }
    }
    
    /// <remarks/>
    public string reldate {
        get {
            return this.reldateField1;
        }
        set {
            this.reldateField1 = value;
        }
    }
    
    /// <remarks/>
    public string mindate {
        get {
            return this.mindateField1;
        }
        set {
            this.mindateField1 = value;
        }
    }
    
    /// <remarks/>
    public string maxdate {
        get {
            return this.maxdateField1;
        }
        set {
            this.maxdateField1 = value;
        }
    }
    
    /// <remarks/>
    public string datetype {
        get {
            return this.datetypeField1;
        }
        set {
            this.datetypeField1 = value;
        }
    }
    
    /// <remarks/>
    public string term {
        get {
            return this.termField4;
        }
        set {
            this.termField4 = value;
        }
    }
    
    /// <remarks/>
    public string dbfrom {
        get {
            return this.dbfromField;
        }
        set {
            this.dbfromField = value;
        }
    }
    
    /// <remarks/>
    public string linkname {
        get {
            return this.linknameField;
        }
        set {
            this.linknameField = value;
        }
    }
    
    /// <remarks/>
    public string WebEnv {
        get {
            return this.webEnvField3;
        }
        set {
            this.webEnvField3 = value;
        }
    }
    
    /// <remarks/>
    public string query_key {
        get {
            return this.query_keyField1;
        }
        set {
            this.query_keyField1 = value;
        }
    }
    
    /// <remarks/>
    public string cmd {
        get {
            return this.cmdField;
        }
        set {
            this.cmdField = value;
        }
    }
    
    /// <remarks/>
    public string tool {
        get {
            return this.toolField4;
        }
        set {
            this.toolField4 = value;
        }
    }
    
    /// <remarks/>
    public string email {
        get {
            return this.emailField4;
        }
        set {
            this.emailField4 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/elink")]
[System.Xml.Serialization.XmlRootAttribute("eLinkResult", Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/elink")]
public partial class MessageELinkResult {
    
    private LinkSetType[] linkSetField;
    
    private string eRRORField8;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LinkSet")]
    public LinkSetType[] LinkSet {
        get {
            return this.linkSetField;
        }
        set {
            this.linkSetField = value;
        }
    }
    
    /// <remarks/>
    public string ERROR {
        get {
            return this.eRRORField8;
        }
        set {
            this.eRRORField8 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/elink")]
public partial class LinkSetType {
    
    private string dbFromField;
    
    private IdType[] idListField1;
    
    private LinkSetDbType[] linkSetDbField;
    
    private LinkSetDbHistoryType[] linkSetDbHistoryField;
    
    private string webEnvField4;
    
    private object[] idUrlListField;
    
    private IdCheckListType idCheckListField;
    
    private string eRRORField7;
    
    /// <remarks/>
    public string DbFrom {
        get {
            return this.dbFromField;
        }
        set {
            this.dbFromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(ElementName="Id", IsNullable=false)]
    public IdType[] IdList {
        get {
            return this.idListField1;
        }
        set {
            this.idListField1 = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LinkSetDb")]
    public LinkSetDbType[] LinkSetDb {
        get {
            return this.linkSetDbField;
        }
        set {
            this.linkSetDbField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LinkSetDbHistory")]
    public LinkSetDbHistoryType[] LinkSetDbHistory {
        get {
            return this.linkSetDbHistoryField;
        }
        set {
            this.linkSetDbHistoryField = value;
        }
    }
    
    /// <remarks/>
    public string WebEnv {
        get {
            return this.webEnvField4;
        }
        set {
            this.webEnvField4 = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(ElementName="IdUrlSet", Type=typeof(IdUrlSetType), IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItem(ElementName="FirstChars", Type=typeof(string[]), IsNullable=false)]
    public object[] IdUrlList {
        get {
            return this.idUrlListField;
        }
        set {
            this.idUrlListField = value;
        }
    }
    
    /// <remarks/>
    public IdCheckListType IdCheckList {
        get {
            return this.idCheckListField;
        }
        set {
            this.idCheckListField = value;
        }
    }
    
    /// <remarks/>
    public string ERROR {
        get {
            return this.eRRORField7;
        }
        set {
            this.eRRORField7 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/elink")]
public partial class IdType {
    
    private IdTypeHasLinkOut hasLinkOutField;
    
    private bool hasLinkOutSpecifiedField;
    
    private IdTypeHasNeighbor hasNeighborField;
    
    private bool hasNeighborSpecifiedField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
    public IdTypeHasLinkOut HasLinkOut {
        get {
            return this.hasLinkOutField;
        }
        set {
            this.hasLinkOutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnore()]
    public virtual bool HasLinkOutSpecified {
        get {
            return this.hasLinkOutSpecifiedField;
        }
        set {
            this.hasLinkOutSpecifiedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
    public IdTypeHasNeighbor HasNeighbor {
        get {
            return this.hasNeighborField;
        }
        set {
            this.hasNeighborField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnore()]
    public virtual bool HasNeighborSpecified {
        get {
            return this.hasNeighborSpecifiedField;
        }
        set {
            this.hasNeighborSpecifiedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/elink")]
public enum IdTypeHasLinkOut {
    
    /// <remarks/>
    Y,
    
    /// <remarks/>
    N,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/elink")]
public enum IdTypeHasNeighbor {
    
    /// <remarks/>
    Y,
    
    /// <remarks/>
    N,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/elink")]
public partial class LinkSetDbType {
    
    private string dbToField1;
    
    private string linkNameField;
    
    private LinkType1[] linkField;
    
    private string infoField;
    
    private string eRRORField4;
    
    /// <remarks/>
    public string DbTo {
        get {
            return this.dbToField1;
        }
        set {
            this.dbToField1 = value;
        }
    }
    
    /// <remarks/>
    public string LinkName {
        get {
            return this.linkNameField;
        }
        set {
            this.linkNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Link")]
    public LinkType1[] Link {
        get {
            return this.linkField;
        }
        set {
            this.linkField = value;
        }
    }
    
    /// <remarks/>
    public string Info {
        get {
            return this.infoField;
        }
        set {
            this.infoField = value;
        }
    }
    
    /// <remarks/>
    public string ERROR {
        get {
            return this.eRRORField4;
        }
        set {
            this.eRRORField4 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute("LinkType", Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/elink")]
public partial class LinkType1 {
    
    private IdType idField3;
    
    private string scoreField;
    
    /// <remarks/>
    public IdType Id {
        get {
            return this.idField3;
        }
        set {
            this.idField3 = value;
        }
    }
    
    /// <remarks/>
    public string Score {
        get {
            return this.scoreField;
        }
        set {
            this.scoreField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/elink")]
public partial class LinkSetDbHistoryType {
    
    private string dbToField2;
    
    private string linkNameField1;
    
    private string queryKeyField2;
    
    private string infoField1;
    
    private string eRRORField5;
    
    /// <remarks/>
    public string DbTo {
        get {
            return this.dbToField2;
        }
        set {
            this.dbToField2 = value;
        }
    }
    
    /// <remarks/>
    public string LinkName {
        get {
            return this.linkNameField1;
        }
        set {
            this.linkNameField1 = value;
        }
    }
    
    /// <remarks/>
    public string QueryKey {
        get {
            return this.queryKeyField2;
        }
        set {
            this.queryKeyField2 = value;
        }
    }
    
    /// <remarks/>
    public string Info {
        get {
            return this.infoField1;
        }
        set {
            this.infoField1 = value;
        }
    }
    
    /// <remarks/>
    public string ERROR {
        get {
            return this.eRRORField5;
        }
        set {
            this.eRRORField5 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/elink")]
public partial class IdUrlSetType {
    
    private IdType idField4;
    
    private object[] itemsField;
    
    /// <remarks/>
    public IdType Id {
        get {
            return this.idField4;
        }
        set {
            this.idField4 = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ObjUrl", Type=typeof(ObjUrlType))]
    [System.Xml.Serialization.XmlElementAttribute("Info", Type=typeof(string))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/elink")]
public partial class ObjUrlType {
    
    private UrlType urlField;
    
    private IconUrlType iconUrlField;
    
    private string linkNameField2;
    
    private string[] subjectTypeField;
    
    private string[] categoryField;
    
    private string[] attributeField;
    
    private ProviderType providerField;
    
    private string subProviderField;
    
    /// <remarks/>
    public UrlType Url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    public IconUrlType IconUrl {
        get {
            return this.iconUrlField;
        }
        set {
            this.iconUrlField = value;
        }
    }
    
    /// <remarks/>
    public string LinkName {
        get {
            return this.linkNameField2;
        }
        set {
            this.linkNameField2 = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SubjectType")]
    public string[] SubjectType {
        get {
            return this.subjectTypeField;
        }
        set {
            this.subjectTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Category")]
    public string[] Category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Attribute")]
    public string[] Attribute {
        get {
            return this.attributeField;
        }
        set {
            this.attributeField = value;
        }
    }
    
    /// <remarks/>
    public ProviderType Provider {
        get {
            return this.providerField;
        }
        set {
            this.providerField = value;
        }
    }
    
    /// <remarks/>
    public string SubProvider {
        get {
            return this.subProviderField;
        }
        set {
            this.subProviderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/elink")]
public partial class UrlType {
    
    private UrlTypeLNG lNGField;
    
    private string valueField1;
    
    /// <remarks/>
    [System.ComponentModel.DefaultValue(UrlTypeLNG.EN)]
    [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
    public UrlTypeLNG LNG {
        get {
            return this.lNGField;
        }
        set {
            this.lNGField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField1;
        }
        set {
            this.valueField1 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/elink")]
public enum UrlTypeLNG {
    
    /// <remarks/>
    DA,
    
    /// <remarks/>
    DE,
    
    /// <remarks/>
    EN,
    
    /// <remarks/>
    EL,
    
    /// <remarks/>
    ES,
    
    /// <remarks/>
    FR,
    
    /// <remarks/>
    IT,
    
    /// <remarks/>
    IW,
    
    /// <remarks/>
    JA,
    
    /// <remarks/>
    NL,
    
    /// <remarks/>
    NO,
    
    /// <remarks/>
    RU,
    
    /// <remarks/>
    SV,
    
    /// <remarks/>
    ZH,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/elink")]
public partial class IconUrlType {
    
    private IconUrlTypeLNG lNGField1;
    
    private string valueField2;
    
    /// <remarks/>
    [System.ComponentModel.DefaultValue(IconUrlTypeLNG.EN)]
    [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
    public IconUrlTypeLNG LNG {
        get {
            return this.lNGField1;
        }
        set {
            this.lNGField1 = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField2;
        }
        set {
            this.valueField2 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/elink")]
public enum IconUrlTypeLNG {
    
    /// <remarks/>
    DA,
    
    /// <remarks/>
    DE,
    
    /// <remarks/>
    EN,
    
    /// <remarks/>
    EL,
    
    /// <remarks/>
    ES,
    
    /// <remarks/>
    FR,
    
    /// <remarks/>
    IT,
    
    /// <remarks/>
    IW,
    
    /// <remarks/>
    JA,
    
    /// <remarks/>
    NL,
    
    /// <remarks/>
    NO,
    
    /// <remarks/>
    RU,
    
    /// <remarks/>
    SV,
    
    /// <remarks/>
    ZH,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/elink")]
public partial class ProviderType {
    
    private string nameField3;
    
    private string nameAbbrField;
    
    private IdType idField5;
    
    private UrlType urlField1;
    
    private IconUrlType iconUrlField1;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField3;
        }
        set {
            this.nameField3 = value;
        }
    }
    
    /// <remarks/>
    public string NameAbbr {
        get {
            return this.nameAbbrField;
        }
        set {
            this.nameAbbrField = value;
        }
    }
    
    /// <remarks/>
    public IdType Id {
        get {
            return this.idField5;
        }
        set {
            this.idField5 = value;
        }
    }
    
    /// <remarks/>
    public UrlType Url {
        get {
            return this.urlField1;
        }
        set {
            this.urlField1 = value;
        }
    }
    
    /// <remarks/>
    public IconUrlType IconUrl {
        get {
            return this.iconUrlField1;
        }
        set {
            this.iconUrlField1 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/elink")]
public partial class IdCheckListType {
    
    private object[] itemsField1;
    
    private string eRRORField6;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Id", Type=typeof(IdType))]
    [System.Xml.Serialization.XmlElementAttribute("IdLinkSet", Type=typeof(IdLinkSetType))]
    public object[] Items {
        get {
            return this.itemsField1;
        }
        set {
            this.itemsField1 = value;
        }
    }
    
    /// <remarks/>
    public string ERROR {
        get {
            return this.eRRORField6;
        }
        set {
            this.eRRORField6 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/elink")]
public partial class IdLinkSetType {
    
    private IdType idField6;
    
    private LinkInfoType[] linkInfoField;
    
    /// <remarks/>
    public IdType Id {
        get {
            return this.idField6;
        }
        set {
            this.idField6 = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LinkInfo")]
    public LinkInfoType[] LinkInfo {
        get {
            return this.linkInfoField;
        }
        set {
            this.linkInfoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/elink")]
public partial class LinkInfoType {
    
    private string dbToField3;
    
    private string linkNameField3;
    
    private string menuTagField;
    
    private string htmlTagField;
    
    private UrlType urlField2;
    
    private string priorityField;
    
    /// <remarks/>
    public string DbTo {
        get {
            return this.dbToField3;
        }
        set {
            this.dbToField3 = value;
        }
    }
    
    /// <remarks/>
    public string LinkName {
        get {
            return this.linkNameField3;
        }
        set {
            this.linkNameField3 = value;
        }
    }
    
    /// <remarks/>
    public string MenuTag {
        get {
            return this.menuTagField;
        }
        set {
            this.menuTagField = value;
        }
    }
    
    /// <remarks/>
    public string HtmlTag {
        get {
            return this.htmlTagField;
        }
        set {
            this.htmlTagField = value;
        }
    }
    
    /// <remarks/>
    public UrlType Url {
        get {
            return this.urlField2;
        }
        set {
            this.urlField2 = value;
        }
    }
    
    /// <remarks/>
    public string Priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/espell")]
[System.Xml.Serialization.XmlRootAttribute("eSpellRequest", Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/espell")]
public partial class MessageESpellRequest {
    
    private string dbField4;
    
    private string termField5;
    
    private string toolField5;
    
    private string emailField5;
    
    /// <remarks/>
    public string db {
        get {
            return this.dbField4;
        }
        set {
            this.dbField4 = value;
        }
    }
    
    /// <remarks/>
    public string term {
        get {
            return this.termField5;
        }
        set {
            this.termField5 = value;
        }
    }
    
    /// <remarks/>
    public string tool {
        get {
            return this.toolField5;
        }
        set {
            this.toolField5 = value;
        }
    }
    
    /// <remarks/>
    public string email {
        get {
            return this.emailField5;
        }
        set {
            this.emailField5 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/espell")]
[System.Xml.Serialization.XmlRootAttribute("eSpellResult", Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/espell")]
public partial class MessageESpellResult {
    
    private string databaseField;
    
    private string queryField;
    
    private string correctedQueryField;
    
    private SpelledQuery spelledQueryField;
    
    private string eRRORField9;
    
    /// <remarks/>
    public string Database {
        get {
            return this.databaseField;
        }
        set {
            this.databaseField = value;
        }
    }
    
    /// <remarks/>
    public string Query {
        get {
            return this.queryField;
        }
        set {
            this.queryField = value;
        }
    }
    
    /// <remarks/>
    public string CorrectedQuery {
        get {
            return this.correctedQueryField;
        }
        set {
            this.correctedQueryField = value;
        }
    }
    
    /// <remarks/>
    public SpelledQuery SpelledQuery {
        get {
            return this.spelledQueryField;
        }
        set {
            this.spelledQueryField = value;
        }
    }
    
    /// <remarks/>
    public string ERROR {
        get {
            return this.eRRORField9;
        }
        set {
            this.eRRORField9 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/espell")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/espell")]
public partial class SpelledQuery {
    
    private ItemsChoiceType[] itemsElementNameField;
    
    private string[] itemsField2;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Replaced")]
    [System.Xml.Serialization.XmlElementAttribute("Original")]
    [System.Xml.Serialization.XmlChoiceIdentifier("ItemsElementName")]
    public string[] Items {
        get {
            return this.itemsField2;
        }
        set {
            this.itemsField2 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/espell", IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <remarks/>
    Replaced,
    
    /// <remarks/>
    Original,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/epost")]
[System.Xml.Serialization.XmlRootAttribute("ePostRequest", Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/epost")]
public partial class MessageEPostRequest {
    
    private string dbField5;
    
    private string idField7;
    
    private string webEnvField5;
    
    private string toolField6;
    
    private string emailField6;
    
    /// <remarks/>
    public string db {
        get {
            return this.dbField5;
        }
        set {
            this.dbField5 = value;
        }
    }
    
    /// <remarks/>
    public string id {
        get {
            return this.idField7;
        }
        set {
            this.idField7 = value;
        }
    }
    
    /// <remarks/>
    public string WebEnv {
        get {
            return this.webEnvField5;
        }
        set {
            this.webEnvField5 = value;
        }
    }
    
    /// <remarks/>
    public string tool {
        get {
            return this.toolField6;
        }
        set {
            this.toolField6 = value;
        }
    }
    
    /// <remarks/>
    public string email {
        get {
            return this.emailField6;
        }
        set {
            this.emailField6 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/epost")]
[System.Xml.Serialization.XmlRootAttribute("ePostResult", Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/epost")]
public partial class MessageEPostResult {
    
    private string[] invalidIdListField;
    
    private string queryKeyField3;
    
    private string webEnvField6;
    
    private string eRRORField10;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(ElementName="Id", IsNullable=false)]
    public string[] InvalidIdList {
        get {
            return this.invalidIdListField;
        }
        set {
            this.invalidIdListField = value;
        }
    }
    
    /// <remarks/>
    public string QueryKey {
        get {
            return this.queryKeyField3;
        }
        set {
            this.queryKeyField3 = value;
        }
    }
    
    /// <remarks/>
    public string WebEnv {
        get {
            return this.webEnvField6;
        }
        set {
            this.webEnvField6 = value;
        }
    }
    
    /// <remarks/>
    public string ERROR {
        get {
            return this.eRRORField10;
        }
        set {
            this.eRRORField10 = value;
        }
    }
}

public partial class run_eGqueryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal run_eGqueryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    public MessageResult Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((MessageResult)(this.results[0]));
        }
    }
}

public delegate void run_eGqueryCompletedEventHandler(object sender, run_eGqueryCompletedEventArgs args);

public partial class run_eInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal run_eInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    public MessageEInfoResult Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((MessageEInfoResult)(this.results[0]));
        }
    }
}

public delegate void run_eInfoCompletedEventHandler(object sender, run_eInfoCompletedEventArgs args);

public partial class run_eSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal run_eSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    public MessageESearchResult Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((MessageESearchResult)(this.results[0]));
        }
    }
}

public delegate void run_eSearchCompletedEventHandler(object sender, run_eSearchCompletedEventArgs args);

public partial class run_eSummaryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal run_eSummaryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    public MessageESummaryResult Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((MessageESummaryResult)(this.results[0]));
        }
    }
}

public delegate void run_eSummaryCompletedEventHandler(object sender, run_eSummaryCompletedEventArgs args);

public partial class run_eLinkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal run_eLinkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    public MessageELinkResult Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((MessageELinkResult)(this.results[0]));
        }
    }
}

public delegate void run_eLinkCompletedEventHandler(object sender, run_eLinkCompletedEventArgs args);

public partial class run_eSpellCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal run_eSpellCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    public MessageESpellResult Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((MessageESpellResult)(this.results[0]));
        }
    }
}

public delegate void run_eSpellCompletedEventHandler(object sender, run_eSpellCompletedEventArgs args);

public partial class run_ePostCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal run_ePostCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    public MessageEPostResult Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((MessageEPostResult)(this.results[0]));
        }
    }
}

public delegate void run_ePostCompletedEventHandler(object sender, run_ePostCompletedEventArgs args);

}	// namespace EhuBio.Database.Ncbi.eUtils {