
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action CargarAction;
	private global::Gtk.Action openAction;
	private global::Gtk.Action saveAction;
	private global::Gtk.Action openAction1;
	private global::Gtk.Action saveAction1;
	private global::Gtk.Action dialogInfoAction;
	private global::Gtk.Action executeAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.Toolbar toolbar2;
	private global::Gtk.Notebook Tabs;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView m_Log;
	private global::Gtk.Label label2;
	private global::Gtk.VPaned vpaned1;
	private global::Gtk.ScrolledWindow GtkScrolledWindow2;
	private global::Gtk.NodeView PeptidesView;
	private global::Gtk.ScrolledWindow GtkScrolledWindow5;
	private global::Gtk.TextView textviewFrag;
	private global::Gtk.Label peptides;
	private global::Gtk.VPaned vpaned2;
	private global::Gtk.ScrolledWindow GtkScrolledWindow3;
	private global::Gtk.NodeView ProteinsView;
	private global::Gtk.ScrolledWindow GtkScrolledWindow4;
	private global::Gtk.TextView textviewProt;
	private global::Gtk.Label Proteins;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.CargarAction = new global::Gtk.Action ("CargarAction", global::Mono.Unix.Catalog.GetString ("Cargar"), null, null);
		this.CargarAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cargar");
		w1.Add (this.CargarAction, null);
		this.openAction = new global::Gtk.Action ("openAction", null, null, "gtk-open");
		this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Load");
		w1.Add (this.openAction, null);
		this.saveAction = new global::Gtk.Action ("saveAction", null, null, "gtk-save");
		w1.Add (this.saveAction, null);
		this.openAction1 = new global::Gtk.Action ("openAction1", null, null, "gtk-open");
		w1.Add (this.openAction1, null);
		this.saveAction1 = new global::Gtk.Action ("saveAction1", null, null, "gtk-save");
		w1.Add (this.saveAction1, null);
		this.dialogInfoAction = new global::Gtk.Action ("dialogInfoAction", null, null, "gtk-dialog-info");
		w1.Add (this.dialogInfoAction, null);
		this.executeAction = new global::Gtk.Action ("executeAction", null, null, "gtk-execute");
		w1.Add (this.executeAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("PAnalyzer");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.DefaultWidth = 800;
		this.DefaultHeight = 600;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar2'><toolitem name='openAction1' action='openAction1'/><toolitem name='saveAction1' action='saveAction1'/><toolitem name='executeAction' action='executeAction'/><toolitem name='dialogInfoAction' action='dialogInfoAction'/></toolbar></ui>");
		this.toolbar2 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar2")));
		this.toolbar2.Name = "toolbar2";
		this.toolbar2.ShowArrow = false;
		this.toolbar2.ToolbarStyle = ((global::Gtk.ToolbarStyle)(2));
		this.vbox1.Add (this.toolbar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.toolbar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.Tabs = new global::Gtk.Notebook ();
		this.Tabs.CanFocus = true;
		this.Tabs.Name = "Tabs";
		this.Tabs.CurrentPage = 0;
		this.Tabs.ShowBorder = false;
		this.Tabs.BorderWidth = ((uint)(10));
		// Container child Tabs.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.m_Log = new global::Gtk.TextView ();
		this.m_Log.CanFocus = true;
		this.m_Log.Name = "m_Log";
		this.m_Log.Editable = false;
		this.GtkScrolledWindow.Add (this.m_Log);
		this.Tabs.Add (this.GtkScrolledWindow);
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Summary");
		this.Tabs.SetTabLabel (this.GtkScrolledWindow, this.label2);
		this.label2.ShowAll ();
		// Container child Tabs.Gtk.Notebook+NotebookChild
		this.vpaned1 = new global::Gtk.VPaned ();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 350;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.PeptidesView = new global::Gtk.NodeView ();
		this.PeptidesView.CanFocus = true;
		this.PeptidesView.Name = "PeptidesView";
		this.GtkScrolledWindow2.Add (this.PeptidesView);
		this.vpaned1.Add (this.GtkScrolledWindow2);
		global::Gtk.Paned.PanedChild w6 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.GtkScrolledWindow2]));
		w6.Resize = false;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.GtkScrolledWindow5 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow5.Name = "GtkScrolledWindow5";
		this.GtkScrolledWindow5.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow5.Gtk.Container+ContainerChild
		this.textviewFrag = new global::Gtk.TextView ();
		this.textviewFrag.CanFocus = true;
		this.textviewFrag.Name = "textviewFrag";
		this.textviewFrag.Editable = false;
		this.textviewFrag.CursorVisible = false;
		this.GtkScrolledWindow5.Add (this.textviewFrag);
		this.vpaned1.Add (this.GtkScrolledWindow5);
		this.Tabs.Add (this.vpaned1);
		global::Gtk.Notebook.NotebookChild w9 = ((global::Gtk.Notebook.NotebookChild)(this.Tabs [this.vpaned1]));
		w9.Position = 1;
		// Notebook tab
		this.peptides = new global::Gtk.Label ();
		this.peptides.Name = "peptides";
		this.peptides.LabelProp = global::Mono.Unix.Catalog.GetString ("Peptides");
		this.Tabs.SetTabLabel (this.vpaned1, this.peptides);
		this.peptides.ShowAll ();
		// Container child Tabs.Gtk.Notebook+NotebookChild
		this.vpaned2 = new global::Gtk.VPaned ();
		this.vpaned2.CanFocus = true;
		this.vpaned2.Name = "vpaned2";
		this.vpaned2.Position = 350;
		// Container child vpaned2.Gtk.Paned+PanedChild
		this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
		this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
		this.ProteinsView = new global::Gtk.NodeView ();
		this.ProteinsView.CanFocus = true;
		this.ProteinsView.Name = "ProteinsView";
		this.GtkScrolledWindow3.Add (this.ProteinsView);
		this.vpaned2.Add (this.GtkScrolledWindow3);
		global::Gtk.Paned.PanedChild w11 = ((global::Gtk.Paned.PanedChild)(this.vpaned2 [this.GtkScrolledWindow3]));
		w11.Resize = false;
		// Container child vpaned2.Gtk.Paned+PanedChild
		this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
		this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
		this.textviewProt = new global::Gtk.TextView ();
		this.textviewProt.CanFocus = true;
		this.textviewProt.Name = "textviewProt";
		this.textviewProt.Editable = false;
		this.textviewProt.CursorVisible = false;
		this.GtkScrolledWindow4.Add (this.textviewProt);
		this.vpaned2.Add (this.GtkScrolledWindow4);
		this.Tabs.Add (this.vpaned2);
		global::Gtk.Notebook.NotebookChild w14 = ((global::Gtk.Notebook.NotebookChild)(this.Tabs [this.vpaned2]));
		w14.Position = 2;
		// Notebook tab
		this.Proteins = new global::Gtk.Label ();
		this.Proteins.Name = "Proteins";
		this.Proteins.LabelProp = global::Mono.Unix.Catalog.GetString ("Proteins");
		this.Tabs.SetTabLabel (this.vpaned2, this.Proteins);
		this.Proteins.ShowAll ();
		this.vbox1.Add (this.Tabs);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.Tabs]));
		w15.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.openAction1.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
		this.saveAction1.Activated += new global::System.EventHandler (this.OnSaveActionActivated);
		this.dialogInfoAction.Activated += new global::System.EventHandler (this.OnDialogInfoActionActivated);
		this.executeAction.Activated += new global::System.EventHandler (this.OnExecuteActionActivated);
	}
}
