//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.16 at 04:53:00 PM CET 
//


package es.ehubio.proteomics.waters.plgs;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="AUTO_QC" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="CALC_INTEN" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="CALC_MASS" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="CURATED" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="MASS_ERROR" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="MASS_ERROR_PPM" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="QUERY_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="SCORE" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="TYPE" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "MASS_MATCH")
public class MASSMATCH {

    @XmlAttribute(name = "AUTO_QC", required = true)
    protected BigInteger autoqc;
    @XmlAttribute(name = "CALC_INTEN")
    protected BigDecimal calcinten;
    @XmlAttribute(name = "CALC_MASS")
    protected BigDecimal calcmass;
    @XmlAttribute(name = "CURATED", required = true)
    protected BigInteger curated;
    @XmlAttribute(name = "ID", required = true)
    protected BigInteger id;
    @XmlAttribute(name = "MASS_ERROR", required = true)
    protected BigDecimal masserror;
    @XmlAttribute(name = "MASS_ERROR_PPM", required = true)
    protected BigDecimal masserrorppm;
    @XmlAttribute(name = "QUERY_ID", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String queryid;
    @XmlAttribute(name = "SCORE", required = true)
    protected BigDecimal score;
    @XmlAttribute(name = "TYPE", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String type;

    /**
     * Gets the value of the autoqc property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAUTOQC() {
        return autoqc;
    }

    /**
     * Sets the value of the autoqc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAUTOQC(BigInteger value) {
        this.autoqc = value;
    }

    /**
     * Gets the value of the calcinten property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCALCINTEN() {
        return calcinten;
    }

    /**
     * Sets the value of the calcinten property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCALCINTEN(BigDecimal value) {
        this.calcinten = value;
    }

    /**
     * Gets the value of the calcmass property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCALCMASS() {
        return calcmass;
    }

    /**
     * Sets the value of the calcmass property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCALCMASS(BigDecimal value) {
        this.calcmass = value;
    }

    /**
     * Gets the value of the curated property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCURATED() {
        return curated;
    }

    /**
     * Sets the value of the curated property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCURATED(BigInteger value) {
        this.curated = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setID(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the masserror property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMASSERROR() {
        return masserror;
    }

    /**
     * Sets the value of the masserror property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMASSERROR(BigDecimal value) {
        this.masserror = value;
    }

    /**
     * Gets the value of the masserrorppm property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMASSERRORPPM() {
        return masserrorppm;
    }

    /**
     * Sets the value of the masserrorppm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMASSERRORPPM(BigDecimal value) {
        this.masserrorppm = value;
    }

    /**
     * Gets the value of the queryid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQUERYID() {
        return queryid;
    }

    /**
     * Sets the value of the queryid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQUERYID(String value) {
        this.queryid = value;
    }

    /**
     * Gets the value of the score property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSCORE() {
        return score;
    }

    /**
     * Sets the value of the score property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSCORE(BigDecimal value) {
        this.score = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTYPE() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTYPE(String value) {
        this.type = value;
    }

}
