//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.16 at 04:53:00 PM CET 
//


package es.ehubio.proteomics.waters.plgs;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ENTRY"/>
 *         &lt;element ref="{}ACCESSION"/>
 *         &lt;element ref="{}DESCRIPTION"/>
 *         &lt;element ref="{}MW"/>
 *         &lt;element ref="{}AQ_FMOLES"/>
 *         &lt;element ref="{}AQ_NGRAMS"/>
 *         &lt;element ref="{}PI"/>
 *         &lt;element ref="{}SEQUENCE"/>
 *         &lt;element ref="{}SEQUENCE_MATCH" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="AUTO_QC" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="CONFIDENCE_LEVEL" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="COVERAGE" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="CURATED" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="FRAG_MATCHES" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="PEP_MATCHES" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="PEP_TOTAL" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="RMS_MASS_ERROR_FRAG" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="RMS_MASS_ERROR_PREC" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="RMS_RT_ERROR_FRAG" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="SCORE" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="VAR_MOD_MATCHES" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "entry",
    "accession",
    "description",
    "mw",
    "aqfmoles",
    "aqngrams",
    "pi",
    "sequence",
    "sequencematch"
})
@XmlRootElement(name = "PROTEIN")
public class PROTEIN {

    @XmlElement(name = "ENTRY", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String entry;
    @XmlElement(name = "ACCESSION", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String accession;
    @XmlElement(name = "DESCRIPTION", required = true)
    protected String description;
    @XmlElement(name = "MW", required = true)
    protected BigDecimal mw;
    @XmlElement(name = "AQ_FMOLES", required = true)
    protected BigDecimal aqfmoles;
    @XmlElement(name = "AQ_NGRAMS", required = true)
    protected BigDecimal aqngrams;
    @XmlElement(name = "PI", required = true)
    protected BigDecimal pi;
    @XmlElement(name = "SEQUENCE", required = true)
    protected String sequence;
    @XmlElement(name = "SEQUENCE_MATCH", required = true)
    protected List<SEQUENCEMATCH> sequencematch;
    @XmlAttribute(name = "AUTO_QC", required = true)
    protected BigInteger autoqc;
    @XmlAttribute(name = "CONFIDENCE_LEVEL", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String confidencelevel;
    @XmlAttribute(name = "COVERAGE", required = true)
    protected BigDecimal coverage;
    @XmlAttribute(name = "CURATED", required = true)
    protected BigInteger curated;
    @XmlAttribute(name = "FRAG_MATCHES", required = true)
    protected BigInteger fragmatches;
    @XmlAttribute(name = "ID", required = true)
    protected BigInteger id;
    @XmlAttribute(name = "PEP_MATCHES", required = true)
    protected BigInteger pepmatches;
    @XmlAttribute(name = "PEP_TOTAL", required = true)
    protected BigInteger peptotal;
    @XmlAttribute(name = "RMS_MASS_ERROR_FRAG", required = true)
    protected BigDecimal rmsmasserrorfrag;
    @XmlAttribute(name = "RMS_MASS_ERROR_PREC", required = true)
    protected BigDecimal rmsmasserrorprec;
    @XmlAttribute(name = "RMS_RT_ERROR_FRAG", required = true)
    protected BigDecimal rmsrterrorfrag;
    @XmlAttribute(name = "SCORE", required = true)
    protected BigDecimal score;
    @XmlAttribute(name = "VAR_MOD_MATCHES", required = true)
    protected BigInteger varmodmatches;

    /**
     * Gets the value of the entry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENTRY() {
        return entry;
    }

    /**
     * Sets the value of the entry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENTRY(String value) {
        this.entry = value;
    }

    /**
     * Gets the value of the accession property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACCESSION() {
        return accession;
    }

    /**
     * Sets the value of the accession property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACCESSION(String value) {
        this.accession = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIPTION(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the mw property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMW() {
        return mw;
    }

    /**
     * Sets the value of the mw property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMW(BigDecimal value) {
        this.mw = value;
    }

    /**
     * Gets the value of the aqfmoles property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAQFMOLES() {
        return aqfmoles;
    }

    /**
     * Sets the value of the aqfmoles property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAQFMOLES(BigDecimal value) {
        this.aqfmoles = value;
    }

    /**
     * Gets the value of the aqngrams property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAQNGRAMS() {
        return aqngrams;
    }

    /**
     * Sets the value of the aqngrams property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAQNGRAMS(BigDecimal value) {
        this.aqngrams = value;
    }

    /**
     * Gets the value of the pi property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPI() {
        return pi;
    }

    /**
     * Sets the value of the pi property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPI(BigDecimal value) {
        this.pi = value;
    }

    /**
     * Gets the value of the sequence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEQUENCE() {
        return sequence;
    }

    /**
     * Sets the value of the sequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEQUENCE(String value) {
        this.sequence = value;
    }

    /**
     * Gets the value of the sequencematch property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sequencematch property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSEQUENCEMATCH().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SEQUENCEMATCH }
     * 
     * 
     */
    public List<SEQUENCEMATCH> getSEQUENCEMATCH() {
        if (sequencematch == null) {
            sequencematch = new ArrayList<SEQUENCEMATCH>();
        }
        return this.sequencematch;
    }

    /**
     * Gets the value of the autoqc property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAUTOQC() {
        return autoqc;
    }

    /**
     * Sets the value of the autoqc property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAUTOQC(BigInteger value) {
        this.autoqc = value;
    }

    /**
     * Gets the value of the confidencelevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCONFIDENCELEVEL() {
        return confidencelevel;
    }

    /**
     * Sets the value of the confidencelevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCONFIDENCELEVEL(String value) {
        this.confidencelevel = value;
    }

    /**
     * Gets the value of the coverage property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCOVERAGE() {
        return coverage;
    }

    /**
     * Sets the value of the coverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCOVERAGE(BigDecimal value) {
        this.coverage = value;
    }

    /**
     * Gets the value of the curated property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCURATED() {
        return curated;
    }

    /**
     * Sets the value of the curated property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCURATED(BigInteger value) {
        this.curated = value;
    }

    /**
     * Gets the value of the fragmatches property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFRAGMATCHES() {
        return fragmatches;
    }

    /**
     * Sets the value of the fragmatches property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFRAGMATCHES(BigInteger value) {
        this.fragmatches = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setID(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the pepmatches property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPEPMATCHES() {
        return pepmatches;
    }

    /**
     * Sets the value of the pepmatches property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPEPMATCHES(BigInteger value) {
        this.pepmatches = value;
    }

    /**
     * Gets the value of the peptotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPEPTOTAL() {
        return peptotal;
    }

    /**
     * Sets the value of the peptotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPEPTOTAL(BigInteger value) {
        this.peptotal = value;
    }

    /**
     * Gets the value of the rmsmasserrorfrag property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRMSMASSERRORFRAG() {
        return rmsmasserrorfrag;
    }

    /**
     * Sets the value of the rmsmasserrorfrag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRMSMASSERRORFRAG(BigDecimal value) {
        this.rmsmasserrorfrag = value;
    }

    /**
     * Gets the value of the rmsmasserrorprec property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRMSMASSERRORPREC() {
        return rmsmasserrorprec;
    }

    /**
     * Sets the value of the rmsmasserrorprec property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRMSMASSERRORPREC(BigDecimal value) {
        this.rmsmasserrorprec = value;
    }

    /**
     * Gets the value of the rmsrterrorfrag property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRMSRTERRORFRAG() {
        return rmsrterrorfrag;
    }

    /**
     * Sets the value of the rmsrterrorfrag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRMSRTERRORFRAG(BigDecimal value) {
        this.rmsrterrorfrag = value;
    }

    /**
     * Gets the value of the score property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSCORE() {
        return score;
    }

    /**
     * Sets the value of the score property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSCORE(BigDecimal value) {
        this.score = value;
    }

    /**
     * Gets the value of the varmodmatches property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVARMODMATCHES() {
        return varmodmatches;
    }

    /**
     * Sets the value of the varmodmatches property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVARMODMATCHES(BigInteger value) {
        this.varmodmatches = value;
    }

}
