//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.16 at 04:53:00 PM CET 
//


package es.ehubio.proteomics.waters.plgs;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}MASS_MATCH" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="CHARGE" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="DRIFT" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="ID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="INTENSITY" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="LE_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="MASS" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *       &lt;attribute name="RETENTION_TIME" use="required" type="{http://www.w3.org/2001/XMLSchema}decimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "massmatch"
})
@XmlRootElement(name = "QUERY_MASS")
public class QUERYMASS {

    @XmlElement(name = "MASS_MATCH")
    protected MASSMATCH massmatch;
    @XmlAttribute(name = "CHARGE", required = true)
    protected BigDecimal charge;
    @XmlAttribute(name = "DRIFT")
    protected BigDecimal drift;
    @XmlAttribute(name = "ID", required = true)
    protected BigInteger id;
    @XmlAttribute(name = "INTENSITY", required = true)
    protected BigDecimal intensity;
    @XmlAttribute(name = "LE_ID", required = true)
    protected BigInteger leid;
    @XmlAttribute(name = "MASS", required = true)
    protected BigDecimal mass;
    @XmlAttribute(name = "RETENTION_TIME", required = true)
    protected BigDecimal retentiontime;

    /**
     * Gets the value of the massmatch property.
     * 
     * @return
     *     possible object is
     *     {@link MASSMATCH }
     *     
     */
    public MASSMATCH getMASSMATCH() {
        return massmatch;
    }

    /**
     * Sets the value of the massmatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link MASSMATCH }
     *     
     */
    public void setMASSMATCH(MASSMATCH value) {
        this.massmatch = value;
    }

    /**
     * Gets the value of the charge property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCHARGE() {
        return charge;
    }

    /**
     * Sets the value of the charge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCHARGE(BigDecimal value) {
        this.charge = value;
    }

    /**
     * Gets the value of the drift property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDRIFT() {
        return drift;
    }

    /**
     * Sets the value of the drift property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDRIFT(BigDecimal value) {
        this.drift = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setID(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the intensity property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getINTENSITY() {
        return intensity;
    }

    /**
     * Sets the value of the intensity property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setINTENSITY(BigDecimal value) {
        this.intensity = value;
    }

    /**
     * Gets the value of the leid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLEID() {
        return leid;
    }

    /**
     * Sets the value of the leid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLEID(BigInteger value) {
        this.leid = value;
    }

    /**
     * Gets the value of the mass property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMASS() {
        return mass;
    }

    /**
     * Sets the value of the mass property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMASS(BigDecimal value) {
        this.mass = value;
    }

    /**
     * Gets the value of the retentiontime property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRETENTIONTIME() {
        return retentiontime;
    }

    /**
     * Sets the value of the retentiontime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRETENTIONTIME(BigDecimal value) {
        this.retentiontime = value;
    }

}
