// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
// This source code was auto-generated by Web Services Description Language Utility
//Mono Framework v4.0.30319.1
//

namespace EhuBio.Database.Ncbi.eFetch.Sequences {

/// <remarks/>
[System.Web.Services.WebServiceBinding(Name="eUtilsServiceSoap", Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class eFetchSequenceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback run_eFetchOperationCompleted;
    
    public eFetchSequenceService() {
        this.Url = "http://eutils.ncbi.nlm.nih.gov/soap/v2.0/soap_adapter_2_0.cgi";
    }
    
    public event run_eFetchCompletedEventHandler run_eFetchCompleted;
    
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("efetch", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
    [return: System.Xml.Serialization.XmlElementAttribute("eFetchResult", Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
    public MessageEFetchResult run_eFetch([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")] MessageEFetchRequest eFetchRequest) {
        object[] results = this.Invoke("run_eFetch", new object[] {
                    eFetchRequest});
        return ((MessageEFetchResult)(results[0]));
    }
    
    public System.IAsyncResult Beginrun_eFetch(MessageEFetchRequest eFetchRequest, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("run_eFetch", new object[] {
                    eFetchRequest}, callback, asyncState);
    }
    
    public MessageEFetchResult Endrun_eFetch(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((MessageEFetchResult)(results[0]));
    }
    
    public void run_eFetchAsync(MessageEFetchRequest eFetchRequest) {
        this.run_eFetchAsync(eFetchRequest, null);
    }
    
    public void run_eFetchAsync(MessageEFetchRequest eFetchRequest, object userState) {
        if ((this.run_eFetchOperationCompleted == null)) {
            this.run_eFetchOperationCompleted = new System.Threading.SendOrPostCallback(this.Onrun_eFetchCompleted);
        }
        this.InvokeAsync("run_eFetch", new object[] {
                    eFetchRequest}, this.run_eFetchOperationCompleted, userState);
    }
    
    private void Onrun_eFetchCompleted(object arg) {
        if ((this.run_eFetchCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.run_eFetchCompleted(this, new run_eFetchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute("eFetchRequest", Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class MessageEFetchRequest {
    
    private string dbField;
    
    private string idField;
    
    private string webEnvField;
    
    private string query_keyField;
    
    private string toolField;
    
    private string emailField;
    
    private string retstartField;
    
    private string retmaxField;
    
    private string rettypeField;
    
    private string strandField;
    
    private string seq_startField;
    
    private string seq_stopField;
    
    private string complexityField;
    
    private string reportField;
    
    /// <remarks/>
    public string db {
        get {
            return this.dbField;
        }
        set {
            this.dbField = value;
        }
    }
    
    /// <remarks/>
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string WebEnv {
        get {
            return this.webEnvField;
        }
        set {
            this.webEnvField = value;
        }
    }
    
    /// <remarks/>
    public string query_key {
        get {
            return this.query_keyField;
        }
        set {
            this.query_keyField = value;
        }
    }
    
    /// <remarks/>
    public string tool {
        get {
            return this.toolField;
        }
        set {
            this.toolField = value;
        }
    }
    
    /// <remarks/>
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    public string retstart {
        get {
            return this.retstartField;
        }
        set {
            this.retstartField = value;
        }
    }
    
    /// <remarks/>
    public string retmax {
        get {
            return this.retmaxField;
        }
        set {
            this.retmaxField = value;
        }
    }
    
    /// <remarks/>
    public string rettype {
        get {
            return this.rettypeField;
        }
        set {
            this.rettypeField = value;
        }
    }
    
    /// <remarks/>
    public string strand {
        get {
            return this.strandField;
        }
        set {
            this.strandField = value;
        }
    }
    
    /// <remarks/>
    public string seq_start {
        get {
            return this.seq_startField;
        }
        set {
            this.seq_startField = value;
        }
    }
    
    /// <remarks/>
    public string seq_stop {
        get {
            return this.seq_stopField;
        }
        set {
            this.seq_stopField = value;
        }
    }
    
    /// <remarks/>
    public string complexity {
        get {
            return this.complexityField;
        }
        set {
            this.complexityField = value;
        }
    }
    
    /// <remarks/>
    public string report {
        get {
            return this.reportField;
        }
        set {
            this.reportField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute("eFetchResult", Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class MessageEFetchResult {
    
    private string eRRORField;
    
    private TSeq[] tSeqSetField;
    
    private GBSeq[] gBSetField;
    
    private INSDSeq[] iNSDSetField;
    
    private string[] idListField;
    
    /// <remarks/>
    public string ERROR {
        get {
            return this.eRRORField;
        }
        set {
            this.eRRORField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public TSeq[] TSeqSet {
        get {
            return this.tSeqSetField;
        }
        set {
            this.tSeqSetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public GBSeq[] GBSet {
        get {
            return this.gBSetField;
        }
        set {
            this.gBSetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public INSDSeq[] INSDSet {
        get {
            return this.iNSDSetField;
        }
        set {
            this.iNSDSetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(ElementName="Id", IsNullable=false)]
    public string[] IdList {
        get {
            return this.idListField;
        }
        set {
            this.idListField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class TSeq {
    
    private TSeqTSeq_seqtype tSeq_seqtypeField;
    
    private string tSeq_giField;
    
    private string tSeq_accverField;
    
    private string tSeq_sidField;
    
    private string tSeq_localField;
    
    private string tSeq_taxidField;
    
    private string tSeq_orgnameField;
    
    private string tSeq_deflineField;
    
    private string tSeq_lengthField;
    
    private string tSeq_sequenceField;
    
    /// <remarks/>
    public TSeqTSeq_seqtype TSeq_seqtype {
        get {
            return this.tSeq_seqtypeField;
        }
        set {
            this.tSeq_seqtypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string TSeq_gi {
        get {
            return this.tSeq_giField;
        }
        set {
            this.tSeq_giField = value;
        }
    }
    
    /// <remarks/>
    public string TSeq_accver {
        get {
            return this.tSeq_accverField;
        }
        set {
            this.tSeq_accverField = value;
        }
    }
    
    /// <remarks/>
    public string TSeq_sid {
        get {
            return this.tSeq_sidField;
        }
        set {
            this.tSeq_sidField = value;
        }
    }
    
    /// <remarks/>
    public string TSeq_local {
        get {
            return this.tSeq_localField;
        }
        set {
            this.tSeq_localField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string TSeq_taxid {
        get {
            return this.tSeq_taxidField;
        }
        set {
            this.tSeq_taxidField = value;
        }
    }
    
    /// <remarks/>
    public string TSeq_orgname {
        get {
            return this.tSeq_orgnameField;
        }
        set {
            this.tSeq_orgnameField = value;
        }
    }
    
    /// <remarks/>
    public string TSeq_defline {
        get {
            return this.tSeq_deflineField;
        }
        set {
            this.tSeq_deflineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string TSeq_length {
        get {
            return this.tSeq_lengthField;
        }
        set {
            this.tSeq_lengthField = value;
        }
    }
    
    /// <remarks/>
    public string TSeq_sequence {
        get {
            return this.tSeq_sequenceField;
        }
        set {
            this.tSeq_sequenceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class TSeqTSeq_seqtype {
    
    private TSeqTSeq_seqtypeValue valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
    public TSeqTSeq_seqtypeValue value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public enum TSeqTSeq_seqtypeValue {
    
    /// <remarks/>
    nucleotide,
    
    /// <remarks/>
    protein,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class GBSeq {
    
    private string gBSeq_locusField;
    
    private string gBSeq_lengthField;
    
    private string gBSeq_strandednessField;
    
    private string gBSeq_moltypeField;
    
    private string gBSeq_topologyField;
    
    private string gBSeq_divisionField;
    
    private string gBSeq_updatedateField;
    
    private string gBSeq_createdateField;
    
    private string gBSeq_updatereleaseField;
    
    private string gBSeq_createreleaseField;
    
    private string gBSeq_definitionField;
    
    private string gBSeq_primaryaccessionField;
    
    private string gBSeq_entryversionField;
    
    private string gBSeq_accessionversionField;
    
    private string[] gBSeq_otherseqidsField;
    
    private string[] gBSeq_secondaryaccessionsField;
    
    private string gBSeq_projectField;
    
    private string[] gBSeq_keywordsField;
    
    private string gBSeq_segmentField;
    
    private string gBSeq_sourceField;
    
    private string gBSeq_organismField;
    
    private string gBSeq_taxonomyField;
    
    private GBReference[] gBSeq_referencesField;
    
    private string gBSeq_commentField;
    
    private GBComment[] gBSeq_commentsetField;
    
    private GBStrucComment[] gBSeq_struccommentsField;
    
    private string gBSeq_primaryField;
    
    private string gBSeq_sourcedbField;
    
    private string gBSeq_databasereferenceField;
    
    private GBFeature[] gBSeq_featuretableField;
    
    private GBFeatureSet[] gBSeq_featuresetField;
    
    private string gBSeq_sequenceField;
    
    private string gBSeq_contigField;
    
    private GBAltSeqData[] gBSeq_altseqField;
    
    /// <remarks/>
    public string GBSeq_locus {
        get {
            return this.gBSeq_locusField;
        }
        set {
            this.gBSeq_locusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string GBSeq_length {
        get {
            return this.gBSeq_lengthField;
        }
        set {
            this.gBSeq_lengthField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_strandedness {
        get {
            return this.gBSeq_strandednessField;
        }
        set {
            this.gBSeq_strandednessField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_moltype {
        get {
            return this.gBSeq_moltypeField;
        }
        set {
            this.gBSeq_moltypeField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_topology {
        get {
            return this.gBSeq_topologyField;
        }
        set {
            this.gBSeq_topologyField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_division {
        get {
            return this.gBSeq_divisionField;
        }
        set {
            this.gBSeq_divisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBSeq_update-date")]
    public string GBSeq_updatedate {
        get {
            return this.gBSeq_updatedateField;
        }
        set {
            this.gBSeq_updatedateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBSeq_create-date")]
    public string GBSeq_createdate {
        get {
            return this.gBSeq_createdateField;
        }
        set {
            this.gBSeq_createdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBSeq_update-release")]
    public string GBSeq_updaterelease {
        get {
            return this.gBSeq_updatereleaseField;
        }
        set {
            this.gBSeq_updatereleaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBSeq_create-release")]
    public string GBSeq_createrelease {
        get {
            return this.gBSeq_createreleaseField;
        }
        set {
            this.gBSeq_createreleaseField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_definition {
        get {
            return this.gBSeq_definitionField;
        }
        set {
            this.gBSeq_definitionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBSeq_primary-accession")]
    public string GBSeq_primaryaccession {
        get {
            return this.gBSeq_primaryaccessionField;
        }
        set {
            this.gBSeq_primaryaccessionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBSeq_entry-version")]
    public string GBSeq_entryversion {
        get {
            return this.gBSeq_entryversionField;
        }
        set {
            this.gBSeq_entryversionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBSeq_accession-version")]
    public string GBSeq_accessionversion {
        get {
            return this.gBSeq_accessionversionField;
        }
        set {
            this.gBSeq_accessionversionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArray(ElementName="GBSeq_other-seqids")]
    [System.Xml.Serialization.XmlArrayItem(ElementName="GBSeqid", IsNullable=false)]
    public string[] GBSeq_otherseqids {
        get {
            return this.gBSeq_otherseqidsField;
        }
        set {
            this.gBSeq_otherseqidsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArray(ElementName="GBSeq_secondary-accessions")]
    [System.Xml.Serialization.XmlArrayItem(ElementName="GBSecondary-accn", IsNullable=false)]
    public string[] GBSeq_secondaryaccessions {
        get {
            return this.gBSeq_secondaryaccessionsField;
        }
        set {
            this.gBSeq_secondaryaccessionsField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_project {
        get {
            return this.gBSeq_projectField;
        }
        set {
            this.gBSeq_projectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(ElementName="GBKeyword", IsNullable=false)]
    public string[] GBSeq_keywords {
        get {
            return this.gBSeq_keywordsField;
        }
        set {
            this.gBSeq_keywordsField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_segment {
        get {
            return this.gBSeq_segmentField;
        }
        set {
            this.gBSeq_segmentField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_source {
        get {
            return this.gBSeq_sourceField;
        }
        set {
            this.gBSeq_sourceField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_organism {
        get {
            return this.gBSeq_organismField;
        }
        set {
            this.gBSeq_organismField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_taxonomy {
        get {
            return this.gBSeq_taxonomyField;
        }
        set {
            this.gBSeq_taxonomyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public GBReference[] GBSeq_references {
        get {
            return this.gBSeq_referencesField;
        }
        set {
            this.gBSeq_referencesField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_comment {
        get {
            return this.gBSeq_commentField;
        }
        set {
            this.gBSeq_commentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArray(ElementName="GBSeq_comment-set")]
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public GBComment[] GBSeq_commentset {
        get {
            return this.gBSeq_commentsetField;
        }
        set {
            this.gBSeq_commentsetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArray(ElementName="GBSeq_struc-comments")]
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public GBStrucComment[] GBSeq_struccomments {
        get {
            return this.gBSeq_struccommentsField;
        }
        set {
            this.gBSeq_struccommentsField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_primary {
        get {
            return this.gBSeq_primaryField;
        }
        set {
            this.gBSeq_primaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBSeq_source-db")]
    public string GBSeq_sourcedb {
        get {
            return this.gBSeq_sourcedbField;
        }
        set {
            this.gBSeq_sourcedbField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBSeq_database-reference")]
    public string GBSeq_databasereference {
        get {
            return this.gBSeq_databasereferenceField;
        }
        set {
            this.gBSeq_databasereferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArray(ElementName="GBSeq_feature-table")]
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public GBFeature[] GBSeq_featuretable {
        get {
            return this.gBSeq_featuretableField;
        }
        set {
            this.gBSeq_featuretableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArray(ElementName="GBSeq_feature-set")]
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public GBFeatureSet[] GBSeq_featureset {
        get {
            return this.gBSeq_featuresetField;
        }
        set {
            this.gBSeq_featuresetField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_sequence {
        get {
            return this.gBSeq_sequenceField;
        }
        set {
            this.gBSeq_sequenceField = value;
        }
    }
    
    /// <remarks/>
    public string GBSeq_contig {
        get {
            return this.gBSeq_contigField;
        }
        set {
            this.gBSeq_contigField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArray(ElementName="GBSeq_alt-seq")]
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public GBAltSeqData[] GBSeq_altseq {
        get {
            return this.gBSeq_altseqField;
        }
        set {
            this.gBSeq_altseqField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class GBReference {
    
    private string gBReference_referenceField;
    
    private string gBReference_positionField;
    
    private string[] gBReference_authorsField;
    
    private string gBReference_consortiumField;
    
    private string gBReference_titleField;
    
    private string gBReference_journalField;
    
    private GBXref[] gBReference_xrefField;
    
    private string gBReference_pubmedField;
    
    private string gBReference_remarkField;
    
    /// <remarks/>
    public string GBReference_reference {
        get {
            return this.gBReference_referenceField;
        }
        set {
            this.gBReference_referenceField = value;
        }
    }
    
    /// <remarks/>
    public string GBReference_position {
        get {
            return this.gBReference_positionField;
        }
        set {
            this.gBReference_positionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(ElementName="GBAuthor", IsNullable=false)]
    public string[] GBReference_authors {
        get {
            return this.gBReference_authorsField;
        }
        set {
            this.gBReference_authorsField = value;
        }
    }
    
    /// <remarks/>
    public string GBReference_consortium {
        get {
            return this.gBReference_consortiumField;
        }
        set {
            this.gBReference_consortiumField = value;
        }
    }
    
    /// <remarks/>
    public string GBReference_title {
        get {
            return this.gBReference_titleField;
        }
        set {
            this.gBReference_titleField = value;
        }
    }
    
    /// <remarks/>
    public string GBReference_journal {
        get {
            return this.gBReference_journalField;
        }
        set {
            this.gBReference_journalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public GBXref[] GBReference_xref {
        get {
            return this.gBReference_xrefField;
        }
        set {
            this.gBReference_xrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string GBReference_pubmed {
        get {
            return this.gBReference_pubmedField;
        }
        set {
            this.gBReference_pubmedField = value;
        }
    }
    
    /// <remarks/>
    public string GBReference_remark {
        get {
            return this.gBReference_remarkField;
        }
        set {
            this.gBReference_remarkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class GBXref {
    
    private string gBXref_dbnameField;
    
    private string gBXref_idField;
    
    /// <remarks/>
    public string GBXref_dbname {
        get {
            return this.gBXref_dbnameField;
        }
        set {
            this.gBXref_dbnameField = value;
        }
    }
    
    /// <remarks/>
    public string GBXref_id {
        get {
            return this.gBXref_idField;
        }
        set {
            this.gBXref_idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class GBComment {
    
    private string gBComment_typeField;
    
    private GBCommentParagraph[] gBComment_paragraphsField;
    
    /// <remarks/>
    public string GBComment_type {
        get {
            return this.gBComment_typeField;
        }
        set {
            this.gBComment_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public GBCommentParagraph[] GBComment_paragraphs {
        get {
            return this.gBComment_paragraphsField;
        }
        set {
            this.gBComment_paragraphsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class GBCommentParagraph {
    
    private GBCommentItem[] gBCommentParagraph_itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public GBCommentItem[] GBCommentParagraph_items {
        get {
            return this.gBCommentParagraph_itemsField;
        }
        set {
            this.gBCommentParagraph_itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class GBCommentItem {
    
    private string gBCommentItem_valueField;
    
    private string gBCommentItem_urlField;
    
    /// <remarks/>
    public string GBCommentItem_value {
        get {
            return this.gBCommentItem_valueField;
        }
        set {
            this.gBCommentItem_valueField = value;
        }
    }
    
    /// <remarks/>
    public string GBCommentItem_url {
        get {
            return this.gBCommentItem_urlField;
        }
        set {
            this.gBCommentItem_urlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class GBStrucComment {
    
    private string gBStrucComment_nameField;
    
    private GBStrucCommentItem[] gBStrucComment_itemsField;
    
    /// <remarks/>
    public string GBStrucComment_name {
        get {
            return this.gBStrucComment_nameField;
        }
        set {
            this.gBStrucComment_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public GBStrucCommentItem[] GBStrucComment_items {
        get {
            return this.gBStrucComment_itemsField;
        }
        set {
            this.gBStrucComment_itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class GBStrucCommentItem {
    
    private string gBStrucCommentItem_tagField;
    
    private string gBStrucCommentItem_valueField;
    
    private string gBStrucCommentItem_urlField;
    
    /// <remarks/>
    public string GBStrucCommentItem_tag {
        get {
            return this.gBStrucCommentItem_tagField;
        }
        set {
            this.gBStrucCommentItem_tagField = value;
        }
    }
    
    /// <remarks/>
    public string GBStrucCommentItem_value {
        get {
            return this.gBStrucCommentItem_valueField;
        }
        set {
            this.gBStrucCommentItem_valueField = value;
        }
    }
    
    /// <remarks/>
    public string GBStrucCommentItem_url {
        get {
            return this.gBStrucCommentItem_urlField;
        }
        set {
            this.gBStrucCommentItem_urlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class GBFeature {
    
    private string gBFeature_keyField;
    
    private string gBFeature_locationField;
    
    private GBInterval[] gBFeature_intervalsField;
    
    private string gBFeature_operatorField;
    
    private GBFeatureGBFeature_partial5 gBFeature_partial5Field;
    
    private GBFeatureGBFeature_partial3 gBFeature_partial3Field;
    
    private GBQualifier[] gBFeature_qualsField;
    
    private GBXref[] gBFeature_xrefsField;
    
    /// <remarks/>
    public string GBFeature_key {
        get {
            return this.gBFeature_keyField;
        }
        set {
            this.gBFeature_keyField = value;
        }
    }
    
    /// <remarks/>
    public string GBFeature_location {
        get {
            return this.gBFeature_locationField;
        }
        set {
            this.gBFeature_locationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public GBInterval[] GBFeature_intervals {
        get {
            return this.gBFeature_intervalsField;
        }
        set {
            this.gBFeature_intervalsField = value;
        }
    }
    
    /// <remarks/>
    public string GBFeature_operator {
        get {
            return this.gBFeature_operatorField;
        }
        set {
            this.gBFeature_operatorField = value;
        }
    }
    
    /// <remarks/>
    public GBFeatureGBFeature_partial5 GBFeature_partial5 {
        get {
            return this.gBFeature_partial5Field;
        }
        set {
            this.gBFeature_partial5Field = value;
        }
    }
    
    /// <remarks/>
    public GBFeatureGBFeature_partial3 GBFeature_partial3 {
        get {
            return this.gBFeature_partial3Field;
        }
        set {
            this.gBFeature_partial3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public GBQualifier[] GBFeature_quals {
        get {
            return this.gBFeature_qualsField;
        }
        set {
            this.gBFeature_qualsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public GBXref[] GBFeature_xrefs {
        get {
            return this.gBFeature_xrefsField;
        }
        set {
            this.gBFeature_xrefsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class GBInterval {
    
    private string gBInterval_fromField;
    
    private string gBInterval_toField;
    
    private string gBInterval_pointField;
    
    private GBIntervalGBInterval_iscomp gBInterval_iscompField;
    
    private GBIntervalGBInterval_interbp gBInterval_interbpField;
    
    private string gBInterval_accessionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string GBInterval_from {
        get {
            return this.gBInterval_fromField;
        }
        set {
            this.gBInterval_fromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string GBInterval_to {
        get {
            return this.gBInterval_toField;
        }
        set {
            this.gBInterval_toField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string GBInterval_point {
        get {
            return this.gBInterval_pointField;
        }
        set {
            this.gBInterval_pointField = value;
        }
    }
    
    /// <remarks/>
    public GBIntervalGBInterval_iscomp GBInterval_iscomp {
        get {
            return this.gBInterval_iscompField;
        }
        set {
            this.gBInterval_iscompField = value;
        }
    }
    
    /// <remarks/>
    public GBIntervalGBInterval_interbp GBInterval_interbp {
        get {
            return this.gBInterval_interbpField;
        }
        set {
            this.gBInterval_interbpField = value;
        }
    }
    
    /// <remarks/>
    public string GBInterval_accession {
        get {
            return this.gBInterval_accessionField;
        }
        set {
            this.gBInterval_accessionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class GBIntervalGBInterval_iscomp {
    
    private GBIntervalGBInterval_iscompValue valueField1;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
    public GBIntervalGBInterval_iscompValue value {
        get {
            return this.valueField1;
        }
        set {
            this.valueField1 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public enum GBIntervalGBInterval_iscompValue {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class GBIntervalGBInterval_interbp {
    
    private GBIntervalGBInterval_interbpValue valueField2;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
    public GBIntervalGBInterval_interbpValue value {
        get {
            return this.valueField2;
        }
        set {
            this.valueField2 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public enum GBIntervalGBInterval_interbpValue {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class GBFeatureGBFeature_partial5 {
    
    private GBFeatureGBFeature_partial5Value valueField3;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
    public GBFeatureGBFeature_partial5Value value {
        get {
            return this.valueField3;
        }
        set {
            this.valueField3 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public enum GBFeatureGBFeature_partial5Value {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class GBFeatureGBFeature_partial3 {
    
    private GBFeatureGBFeature_partial3Value valueField4;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
    public GBFeatureGBFeature_partial3Value value {
        get {
            return this.valueField4;
        }
        set {
            this.valueField4 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public enum GBFeatureGBFeature_partial3Value {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class GBQualifier {
    
    private string gBQualifier_nameField;
    
    private string gBQualifier_valueField;
    
    /// <remarks/>
    public string GBQualifier_name {
        get {
            return this.gBQualifier_nameField;
        }
        set {
            this.gBQualifier_nameField = value;
        }
    }
    
    /// <remarks/>
    public string GBQualifier_value {
        get {
            return this.gBQualifier_valueField;
        }
        set {
            this.gBQualifier_valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class GBFeatureSet {
    
    private string gBFeatureSet_annotsourceField;
    
    private GBFeature[] gBFeatureSet_featuresField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBFeatureSet_annot-source")]
    public string GBFeatureSet_annotsource {
        get {
            return this.gBFeatureSet_annotsourceField;
        }
        set {
            this.gBFeatureSet_annotsourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public GBFeature[] GBFeatureSet_features {
        get {
            return this.gBFeatureSet_featuresField;
        }
        set {
            this.gBFeatureSet_featuresField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class GBAltSeqData {
    
    private string gBAltSeqData_nameField;
    
    private GBAltSeqItem[] gBAltSeqData_itemsField;
    
    /// <remarks/>
    public string GBAltSeqData_name {
        get {
            return this.gBAltSeqData_nameField;
        }
        set {
            this.gBAltSeqData_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public GBAltSeqItem[] GBAltSeqData_items {
        get {
            return this.gBAltSeqData_itemsField;
        }
        set {
            this.gBAltSeqData_itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class GBAltSeqItem {
    
    private GBAltSeqItemGBAltSeqItem_interval gBAltSeqItem_intervalField;
    
    private GBAltSeqItemGBAltSeqItem_isgap gBAltSeqItem_isgapField;
    
    private string gBAltSeqItem_gaplengthField;
    
    private string gBAltSeqItem_gaptypeField;
    
    private string gBAltSeqItem_gaplinkageField;
    
    private string gBAltSeqItem_gapcommentField;
    
    private string gBAltSeqItem_firstaccnField;
    
    private string gBAltSeqItem_lastaccnField;
    
    private string gBAltSeqItem_valueField;
    
    /// <remarks/>
    public GBAltSeqItemGBAltSeqItem_interval GBAltSeqItem_interval {
        get {
            return this.gBAltSeqItem_intervalField;
        }
        set {
            this.gBAltSeqItem_intervalField = value;
        }
    }
    
    /// <remarks/>
    public GBAltSeqItemGBAltSeqItem_isgap GBAltSeqItem_isgap {
        get {
            return this.gBAltSeqItem_isgapField;
        }
        set {
            this.gBAltSeqItem_isgapField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBAltSeqItem_gap-length", DataType="integer")]
    public string GBAltSeqItem_gaplength {
        get {
            return this.gBAltSeqItem_gaplengthField;
        }
        set {
            this.gBAltSeqItem_gaplengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBAltSeqItem_gap-type")]
    public string GBAltSeqItem_gaptype {
        get {
            return this.gBAltSeqItem_gaptypeField;
        }
        set {
            this.gBAltSeqItem_gaptypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBAltSeqItem_gap-linkage")]
    public string GBAltSeqItem_gaplinkage {
        get {
            return this.gBAltSeqItem_gaplinkageField;
        }
        set {
            this.gBAltSeqItem_gaplinkageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBAltSeqItem_gap-comment")]
    public string GBAltSeqItem_gapcomment {
        get {
            return this.gBAltSeqItem_gapcommentField;
        }
        set {
            this.gBAltSeqItem_gapcommentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBAltSeqItem_first-accn")]
    public string GBAltSeqItem_firstaccn {
        get {
            return this.gBAltSeqItem_firstaccnField;
        }
        set {
            this.gBAltSeqItem_firstaccnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GBAltSeqItem_last-accn")]
    public string GBAltSeqItem_lastaccn {
        get {
            return this.gBAltSeqItem_lastaccnField;
        }
        set {
            this.gBAltSeqItem_lastaccnField = value;
        }
    }
    
    /// <remarks/>
    public string GBAltSeqItem_value {
        get {
            return this.gBAltSeqItem_valueField;
        }
        set {
            this.gBAltSeqItem_valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class GBAltSeqItemGBAltSeqItem_interval {
    
    private GBInterval gBIntervalField;
    
    /// <remarks/>
    public GBInterval GBInterval {
        get {
            return this.gBIntervalField;
        }
        set {
            this.gBIntervalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class GBAltSeqItemGBAltSeqItem_isgap {
    
    private GBAltSeqItemGBAltSeqItem_isgapValue valueField5;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
    public GBAltSeqItemGBAltSeqItem_isgapValue value {
        get {
            return this.valueField5;
        }
        set {
            this.valueField5 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public enum GBAltSeqItemGBAltSeqItem_isgapValue {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class INSDSeq {
    
    private string iNSDSeq_locusField;
    
    private string iNSDSeq_lengthField;
    
    private string iNSDSeq_strandednessField;
    
    private string iNSDSeq_moltypeField;
    
    private string iNSDSeq_topologyField;
    
    private string iNSDSeq_divisionField;
    
    private string iNSDSeq_updatedateField;
    
    private string iNSDSeq_createdateField;
    
    private string iNSDSeq_updatereleaseField;
    
    private string iNSDSeq_createreleaseField;
    
    private string iNSDSeq_definitionField;
    
    private string iNSDSeq_primaryaccessionField;
    
    private string iNSDSeq_entryversionField;
    
    private string iNSDSeq_accessionversionField;
    
    private string[] iNSDSeq_otherseqidsField;
    
    private string[] iNSDSeq_secondaryaccessionsField;
    
    private string iNSDSeq_projectField;
    
    private string[] iNSDSeq_keywordsField;
    
    private string iNSDSeq_segmentField;
    
    private string iNSDSeq_sourceField;
    
    private string iNSDSeq_organismField;
    
    private string iNSDSeq_taxonomyField;
    
    private INSDReference[] iNSDSeq_referencesField;
    
    private string iNSDSeq_commentField;
    
    private INSDComment[] iNSDSeq_commentsetField;
    
    private INSDStrucComment[] iNSDSeq_struccommentsField;
    
    private string iNSDSeq_primaryField;
    
    private string iNSDSeq_sourcedbField;
    
    private string iNSDSeq_databasereferenceField;
    
    private INSDFeature[] iNSDSeq_featuretableField;
    
    private INSDFeatureSet[] iNSDSeq_featuresetField;
    
    private string iNSDSeq_sequenceField;
    
    private string iNSDSeq_contigField;
    
    private INSDAltSeqData[] iNSDSeq_altseqField;
    
    /// <remarks/>
    public string INSDSeq_locus {
        get {
            return this.iNSDSeq_locusField;
        }
        set {
            this.iNSDSeq_locusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string INSDSeq_length {
        get {
            return this.iNSDSeq_lengthField;
        }
        set {
            this.iNSDSeq_lengthField = value;
        }
    }
    
    /// <remarks/>
    public string INSDSeq_strandedness {
        get {
            return this.iNSDSeq_strandednessField;
        }
        set {
            this.iNSDSeq_strandednessField = value;
        }
    }
    
    /// <remarks/>
    public string INSDSeq_moltype {
        get {
            return this.iNSDSeq_moltypeField;
        }
        set {
            this.iNSDSeq_moltypeField = value;
        }
    }
    
    /// <remarks/>
    public string INSDSeq_topology {
        get {
            return this.iNSDSeq_topologyField;
        }
        set {
            this.iNSDSeq_topologyField = value;
        }
    }
    
    /// <remarks/>
    public string INSDSeq_division {
        get {
            return this.iNSDSeq_divisionField;
        }
        set {
            this.iNSDSeq_divisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("INSDSeq_update-date")]
    public string INSDSeq_updatedate {
        get {
            return this.iNSDSeq_updatedateField;
        }
        set {
            this.iNSDSeq_updatedateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("INSDSeq_create-date")]
    public string INSDSeq_createdate {
        get {
            return this.iNSDSeq_createdateField;
        }
        set {
            this.iNSDSeq_createdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("INSDSeq_update-release")]
    public string INSDSeq_updaterelease {
        get {
            return this.iNSDSeq_updatereleaseField;
        }
        set {
            this.iNSDSeq_updatereleaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("INSDSeq_create-release")]
    public string INSDSeq_createrelease {
        get {
            return this.iNSDSeq_createreleaseField;
        }
        set {
            this.iNSDSeq_createreleaseField = value;
        }
    }
    
    /// <remarks/>
    public string INSDSeq_definition {
        get {
            return this.iNSDSeq_definitionField;
        }
        set {
            this.iNSDSeq_definitionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("INSDSeq_primary-accession")]
    public string INSDSeq_primaryaccession {
        get {
            return this.iNSDSeq_primaryaccessionField;
        }
        set {
            this.iNSDSeq_primaryaccessionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("INSDSeq_entry-version")]
    public string INSDSeq_entryversion {
        get {
            return this.iNSDSeq_entryversionField;
        }
        set {
            this.iNSDSeq_entryversionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("INSDSeq_accession-version")]
    public string INSDSeq_accessionversion {
        get {
            return this.iNSDSeq_accessionversionField;
        }
        set {
            this.iNSDSeq_accessionversionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArray(ElementName="INSDSeq_other-seqids")]
    [System.Xml.Serialization.XmlArrayItem(ElementName="INSDSeqid", IsNullable=false)]
    public string[] INSDSeq_otherseqids {
        get {
            return this.iNSDSeq_otherseqidsField;
        }
        set {
            this.iNSDSeq_otherseqidsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArray(ElementName="INSDSeq_secondary-accessions")]
    [System.Xml.Serialization.XmlArrayItem(ElementName="INSDSecondary-accn", IsNullable=false)]
    public string[] INSDSeq_secondaryaccessions {
        get {
            return this.iNSDSeq_secondaryaccessionsField;
        }
        set {
            this.iNSDSeq_secondaryaccessionsField = value;
        }
    }
    
    /// <remarks/>
    public string INSDSeq_project {
        get {
            return this.iNSDSeq_projectField;
        }
        set {
            this.iNSDSeq_projectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(ElementName="INSDKeyword", IsNullable=false)]
    public string[] INSDSeq_keywords {
        get {
            return this.iNSDSeq_keywordsField;
        }
        set {
            this.iNSDSeq_keywordsField = value;
        }
    }
    
    /// <remarks/>
    public string INSDSeq_segment {
        get {
            return this.iNSDSeq_segmentField;
        }
        set {
            this.iNSDSeq_segmentField = value;
        }
    }
    
    /// <remarks/>
    public string INSDSeq_source {
        get {
            return this.iNSDSeq_sourceField;
        }
        set {
            this.iNSDSeq_sourceField = value;
        }
    }
    
    /// <remarks/>
    public string INSDSeq_organism {
        get {
            return this.iNSDSeq_organismField;
        }
        set {
            this.iNSDSeq_organismField = value;
        }
    }
    
    /// <remarks/>
    public string INSDSeq_taxonomy {
        get {
            return this.iNSDSeq_taxonomyField;
        }
        set {
            this.iNSDSeq_taxonomyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public INSDReference[] INSDSeq_references {
        get {
            return this.iNSDSeq_referencesField;
        }
        set {
            this.iNSDSeq_referencesField = value;
        }
    }
    
    /// <remarks/>
    public string INSDSeq_comment {
        get {
            return this.iNSDSeq_commentField;
        }
        set {
            this.iNSDSeq_commentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArray(ElementName="INSDSeq_comment-set")]
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public INSDComment[] INSDSeq_commentset {
        get {
            return this.iNSDSeq_commentsetField;
        }
        set {
            this.iNSDSeq_commentsetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArray(ElementName="INSDSeq_struc-comments")]
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public INSDStrucComment[] INSDSeq_struccomments {
        get {
            return this.iNSDSeq_struccommentsField;
        }
        set {
            this.iNSDSeq_struccommentsField = value;
        }
    }
    
    /// <remarks/>
    public string INSDSeq_primary {
        get {
            return this.iNSDSeq_primaryField;
        }
        set {
            this.iNSDSeq_primaryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("INSDSeq_source-db")]
    public string INSDSeq_sourcedb {
        get {
            return this.iNSDSeq_sourcedbField;
        }
        set {
            this.iNSDSeq_sourcedbField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("INSDSeq_database-reference")]
    public string INSDSeq_databasereference {
        get {
            return this.iNSDSeq_databasereferenceField;
        }
        set {
            this.iNSDSeq_databasereferenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArray(ElementName="INSDSeq_feature-table")]
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public INSDFeature[] INSDSeq_featuretable {
        get {
            return this.iNSDSeq_featuretableField;
        }
        set {
            this.iNSDSeq_featuretableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArray(ElementName="INSDSeq_feature-set")]
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public INSDFeatureSet[] INSDSeq_featureset {
        get {
            return this.iNSDSeq_featuresetField;
        }
        set {
            this.iNSDSeq_featuresetField = value;
        }
    }
    
    /// <remarks/>
    public string INSDSeq_sequence {
        get {
            return this.iNSDSeq_sequenceField;
        }
        set {
            this.iNSDSeq_sequenceField = value;
        }
    }
    
    /// <remarks/>
    public string INSDSeq_contig {
        get {
            return this.iNSDSeq_contigField;
        }
        set {
            this.iNSDSeq_contigField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArray(ElementName="INSDSeq_alt-seq")]
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public INSDAltSeqData[] INSDSeq_altseq {
        get {
            return this.iNSDSeq_altseqField;
        }
        set {
            this.iNSDSeq_altseqField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class INSDReference {
    
    private string iNSDReference_referenceField;
    
    private string iNSDReference_positionField;
    
    private string[] iNSDReference_authorsField;
    
    private string iNSDReference_consortiumField;
    
    private string iNSDReference_titleField;
    
    private string iNSDReference_journalField;
    
    private INSDXref[] iNSDReference_xrefField;
    
    private string iNSDReference_pubmedField;
    
    private string iNSDReference_remarkField;
    
    /// <remarks/>
    public string INSDReference_reference {
        get {
            return this.iNSDReference_referenceField;
        }
        set {
            this.iNSDReference_referenceField = value;
        }
    }
    
    /// <remarks/>
    public string INSDReference_position {
        get {
            return this.iNSDReference_positionField;
        }
        set {
            this.iNSDReference_positionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(ElementName="INSDAuthor", IsNullable=false)]
    public string[] INSDReference_authors {
        get {
            return this.iNSDReference_authorsField;
        }
        set {
            this.iNSDReference_authorsField = value;
        }
    }
    
    /// <remarks/>
    public string INSDReference_consortium {
        get {
            return this.iNSDReference_consortiumField;
        }
        set {
            this.iNSDReference_consortiumField = value;
        }
    }
    
    /// <remarks/>
    public string INSDReference_title {
        get {
            return this.iNSDReference_titleField;
        }
        set {
            this.iNSDReference_titleField = value;
        }
    }
    
    /// <remarks/>
    public string INSDReference_journal {
        get {
            return this.iNSDReference_journalField;
        }
        set {
            this.iNSDReference_journalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public INSDXref[] INSDReference_xref {
        get {
            return this.iNSDReference_xrefField;
        }
        set {
            this.iNSDReference_xrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string INSDReference_pubmed {
        get {
            return this.iNSDReference_pubmedField;
        }
        set {
            this.iNSDReference_pubmedField = value;
        }
    }
    
    /// <remarks/>
    public string INSDReference_remark {
        get {
            return this.iNSDReference_remarkField;
        }
        set {
            this.iNSDReference_remarkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class INSDXref {
    
    private string iNSDXref_dbnameField;
    
    private string iNSDXref_idField;
    
    /// <remarks/>
    public string INSDXref_dbname {
        get {
            return this.iNSDXref_dbnameField;
        }
        set {
            this.iNSDXref_dbnameField = value;
        }
    }
    
    /// <remarks/>
    public string INSDXref_id {
        get {
            return this.iNSDXref_idField;
        }
        set {
            this.iNSDXref_idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class INSDComment {
    
    private string iNSDComment_typeField;
    
    private INSDCommentParagraph[] iNSDComment_paragraphsField;
    
    /// <remarks/>
    public string INSDComment_type {
        get {
            return this.iNSDComment_typeField;
        }
        set {
            this.iNSDComment_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public INSDCommentParagraph[] INSDComment_paragraphs {
        get {
            return this.iNSDComment_paragraphsField;
        }
        set {
            this.iNSDComment_paragraphsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class INSDCommentParagraph {
    
    private INSDCommentItem[] iNSDCommentParagraph_itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public INSDCommentItem[] INSDCommentParagraph_items {
        get {
            return this.iNSDCommentParagraph_itemsField;
        }
        set {
            this.iNSDCommentParagraph_itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class INSDCommentItem {
    
    private string iNSDCommentItem_valueField;
    
    private string iNSDCommentItem_urlField;
    
    /// <remarks/>
    public string INSDCommentItem_value {
        get {
            return this.iNSDCommentItem_valueField;
        }
        set {
            this.iNSDCommentItem_valueField = value;
        }
    }
    
    /// <remarks/>
    public string INSDCommentItem_url {
        get {
            return this.iNSDCommentItem_urlField;
        }
        set {
            this.iNSDCommentItem_urlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class INSDStrucComment {
    
    private string iNSDStrucComment_nameField;
    
    private INSDStrucCommentItem[] iNSDStrucComment_itemsField;
    
    /// <remarks/>
    public string INSDStrucComment_name {
        get {
            return this.iNSDStrucComment_nameField;
        }
        set {
            this.iNSDStrucComment_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public INSDStrucCommentItem[] INSDStrucComment_items {
        get {
            return this.iNSDStrucComment_itemsField;
        }
        set {
            this.iNSDStrucComment_itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class INSDStrucCommentItem {
    
    private string iNSDStrucCommentItem_tagField;
    
    private string iNSDStrucCommentItem_valueField;
    
    private string iNSDStrucCommentItem_urlField;
    
    /// <remarks/>
    public string INSDStrucCommentItem_tag {
        get {
            return this.iNSDStrucCommentItem_tagField;
        }
        set {
            this.iNSDStrucCommentItem_tagField = value;
        }
    }
    
    /// <remarks/>
    public string INSDStrucCommentItem_value {
        get {
            return this.iNSDStrucCommentItem_valueField;
        }
        set {
            this.iNSDStrucCommentItem_valueField = value;
        }
    }
    
    /// <remarks/>
    public string INSDStrucCommentItem_url {
        get {
            return this.iNSDStrucCommentItem_urlField;
        }
        set {
            this.iNSDStrucCommentItem_urlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class INSDFeature {
    
    private string iNSDFeature_keyField;
    
    private string iNSDFeature_locationField;
    
    private INSDInterval[] iNSDFeature_intervalsField;
    
    private string iNSDFeature_operatorField;
    
    private INSDFeatureINSDFeature_partial5 iNSDFeature_partial5Field;
    
    private INSDFeatureINSDFeature_partial3 iNSDFeature_partial3Field;
    
    private INSDQualifier[] iNSDFeature_qualsField;
    
    private INSDXref[] iNSDFeature_xrefsField;
    
    /// <remarks/>
    public string INSDFeature_key {
        get {
            return this.iNSDFeature_keyField;
        }
        set {
            this.iNSDFeature_keyField = value;
        }
    }
    
    /// <remarks/>
    public string INSDFeature_location {
        get {
            return this.iNSDFeature_locationField;
        }
        set {
            this.iNSDFeature_locationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public INSDInterval[] INSDFeature_intervals {
        get {
            return this.iNSDFeature_intervalsField;
        }
        set {
            this.iNSDFeature_intervalsField = value;
        }
    }
    
    /// <remarks/>
    public string INSDFeature_operator {
        get {
            return this.iNSDFeature_operatorField;
        }
        set {
            this.iNSDFeature_operatorField = value;
        }
    }
    
    /// <remarks/>
    public INSDFeatureINSDFeature_partial5 INSDFeature_partial5 {
        get {
            return this.iNSDFeature_partial5Field;
        }
        set {
            this.iNSDFeature_partial5Field = value;
        }
    }
    
    /// <remarks/>
    public INSDFeatureINSDFeature_partial3 INSDFeature_partial3 {
        get {
            return this.iNSDFeature_partial3Field;
        }
        set {
            this.iNSDFeature_partial3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public INSDQualifier[] INSDFeature_quals {
        get {
            return this.iNSDFeature_qualsField;
        }
        set {
            this.iNSDFeature_qualsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public INSDXref[] INSDFeature_xrefs {
        get {
            return this.iNSDFeature_xrefsField;
        }
        set {
            this.iNSDFeature_xrefsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class INSDInterval {
    
    private string iNSDInterval_fromField;
    
    private string iNSDInterval_toField;
    
    private string iNSDInterval_pointField;
    
    private INSDIntervalINSDInterval_iscomp iNSDInterval_iscompField;
    
    private INSDIntervalINSDInterval_interbp iNSDInterval_interbpField;
    
    private string iNSDInterval_accessionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string INSDInterval_from {
        get {
            return this.iNSDInterval_fromField;
        }
        set {
            this.iNSDInterval_fromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string INSDInterval_to {
        get {
            return this.iNSDInterval_toField;
        }
        set {
            this.iNSDInterval_toField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string INSDInterval_point {
        get {
            return this.iNSDInterval_pointField;
        }
        set {
            this.iNSDInterval_pointField = value;
        }
    }
    
    /// <remarks/>
    public INSDIntervalINSDInterval_iscomp INSDInterval_iscomp {
        get {
            return this.iNSDInterval_iscompField;
        }
        set {
            this.iNSDInterval_iscompField = value;
        }
    }
    
    /// <remarks/>
    public INSDIntervalINSDInterval_interbp INSDInterval_interbp {
        get {
            return this.iNSDInterval_interbpField;
        }
        set {
            this.iNSDInterval_interbpField = value;
        }
    }
    
    /// <remarks/>
    public string INSDInterval_accession {
        get {
            return this.iNSDInterval_accessionField;
        }
        set {
            this.iNSDInterval_accessionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class INSDIntervalINSDInterval_iscomp {
    
    private INSDIntervalINSDInterval_iscompValue valueField6;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
    public INSDIntervalINSDInterval_iscompValue value {
        get {
            return this.valueField6;
        }
        set {
            this.valueField6 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public enum INSDIntervalINSDInterval_iscompValue {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class INSDIntervalINSDInterval_interbp {
    
    private INSDIntervalINSDInterval_interbpValue valueField7;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
    public INSDIntervalINSDInterval_interbpValue value {
        get {
            return this.valueField7;
        }
        set {
            this.valueField7 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public enum INSDIntervalINSDInterval_interbpValue {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class INSDFeatureINSDFeature_partial5 {
    
    private INSDFeatureINSDFeature_partial5Value valueField8;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
    public INSDFeatureINSDFeature_partial5Value value {
        get {
            return this.valueField8;
        }
        set {
            this.valueField8 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public enum INSDFeatureINSDFeature_partial5Value {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class INSDFeatureINSDFeature_partial3 {
    
    private INSDFeatureINSDFeature_partial3Value valueField9;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
    public INSDFeatureINSDFeature_partial3Value value {
        get {
            return this.valueField9;
        }
        set {
            this.valueField9 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public enum INSDFeatureINSDFeature_partial3Value {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class INSDQualifier {
    
    private string iNSDQualifier_nameField;
    
    private string iNSDQualifier_valueField;
    
    /// <remarks/>
    public string INSDQualifier_name {
        get {
            return this.iNSDQualifier_nameField;
        }
        set {
            this.iNSDQualifier_nameField = value;
        }
    }
    
    /// <remarks/>
    public string INSDQualifier_value {
        get {
            return this.iNSDQualifier_valueField;
        }
        set {
            this.iNSDQualifier_valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class INSDFeatureSet {
    
    private string iNSDFeatureSet_annotsourceField;
    
    private INSDFeature[] iNSDFeatureSet_featuresField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("INSDFeatureSet_annot-source")]
    public string INSDFeatureSet_annotsource {
        get {
            return this.iNSDFeatureSet_annotsourceField;
        }
        set {
            this.iNSDFeatureSet_annotsourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public INSDFeature[] INSDFeatureSet_features {
        get {
            return this.iNSDFeatureSet_featuresField;
        }
        set {
            this.iNSDFeatureSet_featuresField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class INSDAltSeqData {
    
    private string iNSDAltSeqData_nameField;
    
    private INSDAltSeqItem[] iNSDAltSeqData_itemsField;
    
    /// <remarks/>
    public string INSDAltSeqData_name {
        get {
            return this.iNSDAltSeqData_nameField;
        }
        set {
            this.iNSDAltSeqData_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItem(IsNullable=false)]
    public INSDAltSeqItem[] INSDAltSeqData_items {
        get {
            return this.iNSDAltSeqData_itemsField;
        }
        set {
            this.iNSDAltSeqData_itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class INSDAltSeqItem {
    
    private INSDAltSeqItemINSDAltSeqItem_interval iNSDAltSeqItem_intervalField;
    
    private INSDAltSeqItemINSDAltSeqItem_isgap iNSDAltSeqItem_isgapField;
    
    private string iNSDAltSeqItem_gaplengthField;
    
    private string iNSDAltSeqItem_gaptypeField;
    
    private string iNSDAltSeqItem_gaplinkageField;
    
    private string iNSDAltSeqItem_gapcommentField;
    
    private string iNSDAltSeqItem_firstaccnField;
    
    private string iNSDAltSeqItem_lastaccnField;
    
    private string iNSDAltSeqItem_valueField;
    
    /// <remarks/>
    public INSDAltSeqItemINSDAltSeqItem_interval INSDAltSeqItem_interval {
        get {
            return this.iNSDAltSeqItem_intervalField;
        }
        set {
            this.iNSDAltSeqItem_intervalField = value;
        }
    }
    
    /// <remarks/>
    public INSDAltSeqItemINSDAltSeqItem_isgap INSDAltSeqItem_isgap {
        get {
            return this.iNSDAltSeqItem_isgapField;
        }
        set {
            this.iNSDAltSeqItem_isgapField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("INSDAltSeqItem_gap-length", DataType="integer")]
    public string INSDAltSeqItem_gaplength {
        get {
            return this.iNSDAltSeqItem_gaplengthField;
        }
        set {
            this.iNSDAltSeqItem_gaplengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("INSDAltSeqItem_gap-type")]
    public string INSDAltSeqItem_gaptype {
        get {
            return this.iNSDAltSeqItem_gaptypeField;
        }
        set {
            this.iNSDAltSeqItem_gaptypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("INSDAltSeqItem_gap-linkage")]
    public string INSDAltSeqItem_gaplinkage {
        get {
            return this.iNSDAltSeqItem_gaplinkageField;
        }
        set {
            this.iNSDAltSeqItem_gaplinkageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("INSDAltSeqItem_gap-comment")]
    public string INSDAltSeqItem_gapcomment {
        get {
            return this.iNSDAltSeqItem_gapcommentField;
        }
        set {
            this.iNSDAltSeqItem_gapcommentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("INSDAltSeqItem_first-accn")]
    public string INSDAltSeqItem_firstaccn {
        get {
            return this.iNSDAltSeqItem_firstaccnField;
        }
        set {
            this.iNSDAltSeqItem_firstaccnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("INSDAltSeqItem_last-accn")]
    public string INSDAltSeqItem_lastaccn {
        get {
            return this.iNSDAltSeqItem_lastaccnField;
        }
        set {
            this.iNSDAltSeqItem_lastaccnField = value;
        }
    }
    
    /// <remarks/>
    public string INSDAltSeqItem_value {
        get {
            return this.iNSDAltSeqItem_valueField;
        }
        set {
            this.iNSDAltSeqItem_valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class INSDAltSeqItemINSDAltSeqItem_interval {
    
    private INSDInterval iNSDIntervalField;
    
    /// <remarks/>
    public INSDInterval INSDInterval {
        get {
            return this.iNSDIntervalField;
        }
        set {
            this.iNSDIntervalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public partial class INSDAltSeqItemINSDAltSeqItem_isgap {
    
    private INSDAltSeqItemINSDAltSeqItem_isgapValue valueField10;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Namespace="")]
    public INSDAltSeqItemINSDAltSeqItem_isgapValue value {
        get {
            return this.valueField10;
        }
        set {
            this.valueField10 = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ncbi.nlm.nih.gov/soap/eutils/efetch_seq")]
public enum INSDAltSeqItemINSDAltSeqItem_isgapValue {
    
    /// <remarks/>
    @true,
    
    /// <remarks/>
    @false,
}

public partial class run_eFetchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal run_eFetchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    public MessageEFetchResult Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((MessageEFetchResult)(this.results[0]));
        }
    }
}

public delegate void run_eFetchCompletedEventHandler(object sender, run_eFetchCompletedEventArgs args);

}	// namespace EhuBio.Database.Ncbi.eFetch.Sequences